//! Per-kernel goldens against the reference tokenisers.
//!
//! Generated by `benchmarks/scripts/gen_tokenize_goldens.py` (run manually in
//! the repo `.venv`, never in CI) and committed under
//! `scx-loader/tests/data/tokenize/`. Each file is pinned by a blake3-64 prefix
//! over its raw bytes, so a regenerated fixture cannot land silently — the same
//! mechanism `encoder_crop_golden.json` and `downsample_golden.json` use.
//!
//! # What each file claims, and why three of them claim less than "exact"
//!
//! The generator transcribes each reference's own kernel rather than importing
//! it, because none of `scgpt` / `geneformer` / UCE is installed anywhere on
//! this machine. That is weaker than an import and is stamped into every file's
//! `_provenance` block. On top of that, three of the references are stochastic
//! or underdetermined and admit no exact match at all:
//!
//! | file | claim |
//! |---|---|
//! | `crop_golden.json` | exact — `np.lexsort` is deterministic |
//! | `rank_golden.json` | exact **per equal-value run**; `np.argsort`'s default kind is quicksort, so the reference's order inside a run follows no rule |
//! | `bin_golden.json` | exact for the quantile edges and both digitize bounds; the randomised form is checked by **bracketing the reference's own draws** |
//! | `sample_reference.json` | distributional only — `np.random.choice` reads numpy's global RNG |
//!
//! The bracketing check is the strongest thing available for the bin kernel and
//! is not circular: the draws in the fixture were produced by scGPT's own
//! `_digitize(side="both")` formula, and this file asserts that SCX's `Left` and
//! `Right` bound every one of them.

use super::*;
use crate::tokenize::bin::{BinEdges, BinTie};
use crate::tokenize::crop::{CropConfig, CropIn, CropOut};
use crate::tokenize::rank::PerGeneNorm;
use serde_json::Value;

const CROP_GOLDEN_BLAKE3_PREFIX: &str = "1090c3a399faff12";
const RANK_GOLDEN_BLAKE3_PREFIX: &str = "cb25a0b653484ce4";
const BIN_GOLDEN_BLAKE3_PREFIX: &str = "13fbb730650b0161";
const SAMPLE_REFERENCE_BLAKE3_PREFIX: &str = "9a2cc310f735c37c";

/// Read a golden and assert its bytes have not drifted.
fn load(name: &str, expect_prefix: &str) -> Value {
    let path = format!("{}/tests/data/tokenize/{name}", env!("CARGO_MANIFEST_DIR"));
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("reading {path}: {e}"));
    let digest = blake3::hash(raw.as_bytes()).to_hex().to_string();
    assert_eq!(
        &digest[..16],
        expect_prefix,
        "{name} changed. If deliberate: regenerate with `.venv/bin/python \
         benchmarks/scripts/gen_tokenize_goldens.py`, read the new prefix off its \
         output, update the constant here, and check whether the change alters \
         what `docs/tokenize.md` claims."
    );
    serde_json::from_str(&raw).unwrap_or_else(|e| panic!("parsing {path}: {e}"))
}

fn i32s(v: &Value) -> Vec<i32> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_i64().unwrap() as i32)
        .collect()
}

fn i64s(v: &Value) -> Vec<i64> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_i64().unwrap())
        .collect()
}

fn f32s(v: &Value) -> Vec<f32> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_f64().unwrap() as f32)
        .collect()
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_f64().unwrap())
        .collect()
}

fn u8s(v: &Value) -> Vec<u8> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_u64().unwrap() as u8)
        .collect()
}

fn cases(g: &Value) -> &Vec<Value> {
    g["cases"].as_array().unwrap()
}

/// Every golden must carry at least the case count it was generated with.
///
/// Without this, adding a case to the generator and forgetting to regenerate
/// leaves the new case silently untested — the trap `downsample_tests.rs`
/// documents.
#[test]
fn every_golden_carries_the_expected_number_of_cases() {
    for (name, prefix, n) in [
        ("crop_golden.json", CROP_GOLDEN_BLAKE3_PREFIX, 9usize),
        ("rank_golden.json", RANK_GOLDEN_BLAKE3_PREFIX, 8),
        ("bin_golden.json", BIN_GOLDEN_BLAKE3_PREFIX, 7),
        ("sample_reference.json", SAMPLE_REFERENCE_BLAKE3_PREFIX, 5),
    ] {
        assert_eq!(cases(&load(name, prefix)).len(), n, "{name}");
    }
}

#[test]
fn crop_matches_the_reference_exactly() {
    let g = load("crop_golden.json", CROP_GOLDEN_BLAKE3_PREFIX);
    for case in cases(&g) {
        let name = case["name"].as_str().unwrap();
        let gene_ids = i32s(&case["gene_ids"]);
        let values = f32s(&case["values"]);
        let k = case["k"].as_u64().unwrap() as usize;
        let n_genes_total = case["n_genes_total"].as_i64().unwrap();
        let mut ids = vec![0i64; k];
        let mut vals = vec![0f32; k];
        let mut mask = vec![0u8; k];
        let mut pad = vec![0u8; k];
        crop::top_k(
            &CropIn {
                row: CsrRow {
                    gene_ids: &gene_ids,
                    values: &values,
                },
                emit: &values,
                withheld: None,
                hide_readout: false,
            },
            &CropConfig { k, n_genes_total },
            &mut Vec::new(),
            &mut CropOut {
                ids: &mut ids,
                values: &mut vals,
                mask: &mut mask,
                pad: &mut pad,
            },
        );
        let e = &case["expected"];
        assert_eq!(ids, i64s(&e["ids"]), "{name} ids");
        assert_eq!(vals, f32s(&e["values"]), "{name} values");
        assert_eq!(mask, u8s(&e["mask"]), "{name} mask");
        assert_eq!(pad, u8s(&e["pad"]), "{name} pad");
    }
}

#[test]
fn rank_matches_the_reference_within_every_equal_value_run() {
    let g = load("rank_golden.json", RANK_GOLDEN_BLAKE3_PREFIX);
    let mut saw_tie_free = false;
    let mut saw_tied = false;
    for case in cases(&g) {
        let name = case["name"].as_str().unwrap();
        let gene_ids = i32s(&case["gene_ids"]);
        let counts = f32s(&case["counts"]);
        let stats = f32s(&case["gene_stats"]);
        let l_max = case["l_max"].as_u64().unwrap() as usize;
        let target_sum = case["target_sum"].as_f64().unwrap();
        let norm = PerGeneNorm::new(stats.into(), "golden").unwrap();
        let mut out = vec![0i64; l_max];
        let n = rank::rank_tokens(
            CsrRow {
                gene_ids: &gene_ids,
                values: &counts,
            },
            &norm,
            target_sum,
            &mut Vec::new(),
            &mut Vec::new(),
            &mut out,
        )
        .unwrap();
        assert_eq!(
            n,
            case["expected_len"].as_u64().unwrap() as usize,
            "{name} length"
        );

        // Walk the reference's equal-value runs in order. Within a run the
        // reference has no rule, so compare the run's ids as a sorted set — and
        // SCX's declared rule (id ascending) means its own order inside the run
        // must already BE that sorted list, which is the stronger assertion made
        // below.
        let mut cursor = 0usize;
        let tie_free = case["tie_free"].as_bool().unwrap();
        for group in case["expected_groups"].as_array().unwrap() {
            let want = i64s(group);
            let got = &out[cursor..cursor + want.len()];
            let mut sorted = got.to_vec();
            sorted.sort_unstable();
            assert_eq!(sorted, want, "{name} run at {cursor}");
            assert_eq!(
                got,
                want.as_slice(),
                "{name}: SCX's declared tie rule is gene id ascending, so the run \
                 at {cursor} should already be in that order"
            );
            cursor += want.len();
        }
        assert_eq!(cursor, n, "{name}: runs must tile the output");
        saw_tie_free |= tie_free && n > 1;
        saw_tied |= !tie_free;
    }
    // Anti-vacuity: the exactness claim and the run claim each need a case.
    assert!(saw_tie_free, "no tie-free case with more than one token");
    assert!(
        saw_tied,
        "no tied case, so the run logic was never exercised"
    );
}

#[test]
fn bin_edges_and_both_digitize_bounds_match_the_reference_exactly() {
    let g = load("bin_golden.json", BIN_GOLDEN_BLAKE3_PREFIX);
    for case in cases(&g) {
        let name = case["name"].as_str().unwrap();
        let values = f32s(&case["values"]);
        let n_bins = case["n_bins"].as_u64().unwrap() as usize;
        // The reference bins only the non-zero entries; SCX bins the whole row
        // and leaves zeros at bin 0, so compare at the non-zero positions.
        let nz: Vec<usize> = (0..values.len()).filter(|&i| values[i] != 0.0).collect();
        for (tie, key) in [
            (BinTie::Left, "expected_left"),
            (BinTie::Right, "expected_right"),
        ] {
            let mut out = vec![0i64; values.len()];
            bin::bin_values(
                &values,
                BinEdges::PerCellQuantile,
                n_bins,
                tie,
                &mut Vec::new(),
                &mut out,
            )
            .unwrap();
            let got: Vec<i64> = nz.iter().map(|&i| out[i]).collect();
            assert_eq!(got, i64s(&case[key]), "{name} {key}");
        }
    }
}

#[test]
fn scx_bounds_bracket_every_draw_the_reference_produced() {
    // The bin kernel's real parity claim. The draws in the fixture came out of
    // scGPT's own `_digitize(side="both")`; this asserts SCX's two deterministic
    // bounds contain all of them, which is the most any implementation can say
    // about a kernel that reads numpy's global RNG.
    let g = load("bin_golden.json", BIN_GOLDEN_BLAKE3_PREFIX);
    let mut total_draws = 0usize;
    let mut widest_bracket = 0i64;
    let mut distinct_values_seen = std::collections::BTreeSet::new();
    for case in cases(&g) {
        let name = case["name"].as_str().unwrap();
        let left = i64s(&case["expected_left"]);
        let right = i64s(&case["expected_right"]);
        for draw in case["reference_randomised_draws"].as_array().unwrap() {
            let d = i64s(draw);
            assert_eq!(d.len(), left.len(), "{name} draw width");
            for i in 0..d.len() {
                assert!(
                    d[i] >= right[i] && d[i] <= left[i],
                    "{name} position {i}: reference drew {} outside SCX's [{}, {}]",
                    d[i],
                    right[i],
                    left[i]
                );
                total_draws += 1;
                widest_bracket = widest_bracket.max(left[i] - right[i]);
                if left[i] != right[i] {
                    distinct_values_seen.insert((name.to_string(), i, d[i]));
                }
            }
        }
    }
    assert!(total_draws > 0, "no reference draws in the fixture");
    // Anti-vacuity, stated as a property rather than as a share of positions: a
    // fixture where `left == right` everywhere would satisfy the bracket no
    // matter what the randomisation did, and one where the widest bracket is 1
    // would only ever test a coin flip. The degenerate all-equal-values case
    // gives a bracket of `n_bins - 1`.
    assert!(
        widest_bracket >= 2,
        "widest bracket is {widest_bracket}; the fixture needs at least one \
         position where the reference can land on three or more bins"
    );
    assert!(
        !distinct_values_seen.is_empty(),
        "no position had room to move, so the bracket was never exercised"
    );
}

#[test]
fn the_sampler_reproduces_the_references_probabilities_not_its_draws() {
    // `np.random.choice` reads numpy's global RNG, so the only checkable claim
    // is distributional. The fixture carries the reference's exact normalised
    // weights; this draws from SCX's sampler and checks each gene's empirical
    // frequency against them.
    const N: usize = 60_000;
    let g = load("sample_reference.json", SAMPLE_REFERENCE_BLAKE3_PREFIX);
    let mut checked = 0usize;
    for case in cases(&g) {
        let name = case["name"].as_str().unwrap();
        let gene_ids = i32s(&case["gene_ids"]);
        let counts = f32s(&case["counts"]);
        let probs = f64s(&case["expected_probabilities"]);
        let mut out = vec![0i64; N];
        let drawn = sample::sample_genes(
            CsrRow {
                gene_ids: &gene_ids,
                values: &counts,
            },
            sample::WeightTransform::Log1p,
            20260914,
            0xABCD,
            7,
            &mut Vec::new(),
            &mut out,
        )
        .unwrap();
        if probs.iter().sum::<f64>() == 0.0 {
            assert_eq!(drawn, 0, "{name}: no weight, so nothing should be drawn");
            continue;
        }
        assert_eq!(drawn, N);
        for (i, &gid) in gene_ids.iter().enumerate() {
            let observed = out.iter().filter(|&&x| x == gid as i64).count() as f64 / N as f64;
            let p = probs[i];
            let se = (p * (1.0 - p) / N as f64).sqrt();
            assert!(
                (observed - p).abs() < 5.0 * se + 1e-12,
                "{name} gene {gid}: observed {observed:.5} vs reference {p:.5}"
            );
            checked += 1;
        }
    }
    assert!(checked > 0, "no case exercised the distribution check");
}

// ---------------------------------------------------------------------------
// Frozen SCX goldens for the two seeded kernels
// ---------------------------------------------------------------------------
//
// Source of truth here is **Rust**, the opposite direction from the four files
// above: no reference implementation can produce these, because both kernels
// draw from `ChaCha8Rng` keyed through `crate::seed::row_seed`. What they pin is
// that SCX's own stream has not moved — a changed domain tag, a changed RNG, or
// a reordered `gen()` call would all land here. `downsample_golden.json` is the
// same pattern, and its `row_seed` derivation is shared with these.

const SEEDED_GOLDEN_BLAKE3_PREFIX: &str = "5ee2f769d27e4bdc";

/// The cases, shared by the assertion and the regenerator so the two cannot
/// drift — `downsample_tests.rs`'s rule.
struct SeededCase {
    name: &'static str,
    gene_ids: &'static [i32],
    counts: &'static [f32],
    seed: u64,
    file_identity: u64,
    row: u64,
}

const SEEDED_CASES: &[SeededCase] = &[
    SeededCase {
        name: "two_genes_equal",
        gene_ids: &[3, 8],
        counts: &[5.0, 5.0],
        seed: 1,
        file_identity: 2,
        row: 0,
    },
    SeededCase {
        name: "wide_dynamic_range",
        gene_ids: &[1, 2],
        counts: &[1.0, 1000.0],
        seed: 5,
        file_identity: 6,
        row: 7,
    },
    SeededCase {
        name: "four_genes",
        gene_ids: &[10, 20, 30, 40],
        counts: &[1.0, 3.0, 7.0, 15.0],
        seed: 20260914,
        file_identity: 0xABCD,
        row: 42,
    },
    SeededCase {
        name: "same_cell_different_row_key",
        gene_ids: &[10, 20, 30, 40],
        counts: &[1.0, 3.0, 7.0, 15.0],
        seed: 20260914,
        file_identity: 0xABCD,
        row: 43,
    },
    SeededCase {
        name: "flat_cell_for_the_bin_tiebreak",
        gene_ids: &[1, 2, 3, 4, 5, 6, 7, 8],
        counts: &[4.0; 8],
        seed: 3,
        file_identity: 9,
        row: 11,
    },
];

const SEEDED_N_DRAWS: usize = 12;
const SEEDED_N_BINS: usize = 9;

fn seeded_outputs() -> Vec<(String, Vec<i64>, Vec<i64>)> {
    SEEDED_CASES
        .iter()
        .map(|c| {
            let row = CsrRow {
                gene_ids: c.gene_ids,
                values: c.counts,
            };
            let mut drawn = vec![0i64; SEEDED_N_DRAWS];
            let n = sample::sample_genes(
                row,
                sample::WeightTransform::Log1p,
                c.seed,
                c.file_identity,
                c.row,
                &mut Vec::new(),
                &mut drawn,
            )
            .unwrap();
            drawn.truncate(n);
            let mut bins = vec![0i64; c.counts.len()];
            bin::bin_values(
                c.counts,
                BinEdges::PerCellQuantile,
                SEEDED_N_BINS,
                BinTie::SeededUniform {
                    seed: c.seed,
                    file_identity: c.file_identity,
                    row: c.row,
                },
                &mut Vec::new(),
                &mut bins,
            )
            .unwrap();
            (c.name.to_string(), drawn, bins)
        })
        .collect()
}

fn seeded_golden_text() -> String {
    let cases: Vec<serde_json::Value> = seeded_outputs()
        .into_iter()
        .zip(SEEDED_CASES)
        .map(|((name, drawn, bins), c)| {
            serde_json::json!({
                "name": name,
                "gene_ids": c.gene_ids,
                "counts": c.counts,
                "seed": c.seed,
                "file_identity": c.file_identity,
                "row": c.row,
                "sample_n": SEEDED_N_DRAWS,
                "sample_ids": drawn,
                "bin_n_bins": SEEDED_N_BINS,
                "bin_seeded": bins,
            })
        })
        .collect();
    let payload = serde_json::json!({
        "_comment": "GENERATED FILE - source of truth is Rust. Regenerate with \
                     `cargo test -p scx-loader regenerate_seeded_golden -- --ignored \
                     --nocapture`, then update SEEDED_GOLDEN_BLAKE3_PREFIX. These \
                     values come from ChaCha8Rng keyed through crate::seed::row_seed; \
                     no reference implementation can produce them, so what they pin is \
                     that SCX's own stream has not moved.",
        "cases": cases,
    });
    serde_json::to_string_pretty(&payload).unwrap() + "\n"
}

#[test]
fn seeded_kernels_match_their_frozen_golden() {
    let path = format!(
        "{}/tests/data/tokenize/seeded_golden.json",
        env!("CARGO_MANIFEST_DIR")
    );
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("reading {path}: {e}"));
    let digest = blake3::hash(raw.as_bytes()).to_hex().to_string();
    assert_eq!(
        &digest[..16],
        SEEDED_GOLDEN_BLAKE3_PREFIX,
        "seeded_golden.json changed. If deliberate: regenerate with `cargo test -p \
         scx-loader regenerate_seeded_golden -- --ignored --nocapture`, update the \
         constant, and say in the commit WHY the stream moved — a resumed training \
         run that switches streams is the failure this pins."
    );
    let g: Value = serde_json::from_str(&raw).unwrap();
    let recorded = cases(&g);
    assert_eq!(
        recorded.len(),
        SEEDED_CASES.len(),
        "a case was added to SEEDED_CASES without regenerating the golden, so it is \
         silently untested"
    );
    for (case, (name, drawn, bins)) in recorded.iter().zip(seeded_outputs()) {
        assert_eq!(case["name"].as_str().unwrap(), name);
        assert_eq!(i64s(&case["sample_ids"]), drawn, "{name} sample_ids");
        assert_eq!(i64s(&case["bin_seeded"]), bins, "{name} bin_seeded");
    }
}

/// Regenerate `tests/data/tokenize/seeded_golden.json` and print its prefix.
#[test]
#[ignore = "writes into the source tree; run explicitly to regenerate"]
fn regenerate_seeded_golden() {
    let text = seeded_golden_text();
    let path = format!(
        "{}/tests/data/tokenize/seeded_golden.json",
        env!("CARGO_MANIFEST_DIR")
    );
    std::fs::write(&path, &text).unwrap();
    let digest = blake3::hash(text.as_bytes()).to_hex().to_string();
    println!("wrote {path}");
    println!("SEEDED_GOLDEN_BLAKE3_PREFIX = \"{}\"", &digest[..16]);
}
