[package]
name = "pyscx"
version = "0.1.0"
edition = "2021"
description = "Python bindings for SCX via PyO3"
license.workspace = true
authors.workspace = true

[lib]
name = "pyscx"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { workspace = true }
numpy = { workspace = true }
scx-format = { path = "../scx-format" }
scx-sparse = { path = "../scx-sparse" }
