//! Differential expression (Wilcoxon rank-sum / pdex reference mode).
//!
//! [`cpu`] holds the host implementations and the parity oracle; [`gpu`]
//! (behind the `gpu` feature) holds the GPU orchestration that drives the
//! `scx-gpu` device primitives. Routing is decided by `crate::route`.
//!
//! [`groups`] owns the one definition of "which cells take part" — every
//! kernel, CPU or GPU, dense or sparse, derives its rest denominator and rank
//! pool from it rather than from `n_obs`.

pub mod cpu;
// The external oracle for all three rank-sum kernels (ORG-7.21-3).
// `wilcoxon_reference_values` is the scipy/scanpy table, generated by
// `benchmarks/scripts/generate_de_parity_references.py`; the dense and
// analytic-nnz arms assert against it here and the CUDA arm does so from
// `gpu_tests.rs`.
#[cfg(feature = "gpu")]
pub mod gpu;
pub mod groups;
pub mod pts;
#[cfg(test)]
#[path = "wilcoxon_reference_tests.rs"]
mod wilcoxon_reference_tests;
#[cfg(test)]
#[path = "wilcoxon_reference_values.rs"]
pub(crate) mod wilcoxon_reference_values;

pub use groups::{partition_by_group, GroupPartition};

pub use pts::{
    group_nonzero_counts_csr, group_nonzero_counts_dense, group_nonzero_counts_streaming,
    GroupNonzeroCounts, PtsFractions,
};

pub use cpu::{
    finalize_pdex, merge_diff_exp_results, pdex_ref, pdex_ref_core, pdex_ref_sparse,
    pdex_ref_streaming, wilcoxon_rank_sum, wilcoxon_rank_sum_sparse, wilcoxon_rank_sum_streaming,
    DiffExpResult, PdexRefResult,
};
// Shared inference helpers reused by the NB-GLM Wald + BH steps (spec §7.7–7.8).
pub(crate) use cpu::{benjamini_hochberg, normal_sf};
#[cfg(feature = "gpu")]
pub use gpu::{
    pdex_ref_gpu, pdex_ref_gpu_dense, wilcoxon_rank_sum_gpu, wilcoxon_rank_sum_gpu_dense,
    GpuDeShardInput,
};
