//! Differential expression (Wilcoxon rank-sum / pdex reference mode).
//!
//! [`cpu`] holds the host implementations and the parity oracle; [`gpu`]
//! (behind the `gpu` feature) holds the GPU orchestration that drives the
//! `scx-gpu` device primitives. Routing is decided by `crate::route`.
//!
//! [`groups`] owns the one definition of "which cells take part" — every
//! kernel, CPU or GPU, dense or sparse, derives its rest denominator and rank
//! pool from it rather than from `n_obs`.

use crate::{AccelError, Result};

pub mod cpu;
// The external oracle for all three rank-sum kernels (ORG-7.21-3).
// `wilcoxon_reference_values` is the scipy/scanpy table, generated by
// `benchmarks/scripts/generate_de_parity_references.py`; the dense and
// analytic-nnz arms assert against it here and the CUDA arm does so from
// `gpu_tests.rs`.
#[cfg(feature = "gpu")]
pub mod gpu;
pub mod groups;
pub mod pts;
#[cfg(test)]
#[path = "wilcoxon_reference_tests.rs"]
mod wilcoxon_reference_tests;
#[cfg(test)]
#[path = "wilcoxon_reference_values.rs"]
pub(crate) mod wilcoxon_reference_values;

pub use groups::{partition_by_group, GroupPartition};

/// A cursor over the *visible* rows a shard walk delivers, carrying the two
/// checks that make a source's shard plan falsifiable.
///
/// Every streaming DE pass — CPU Wilcoxon, CPU pdex, the `pts` counting pass,
/// and the three GPU CSR passes — fills an `n_obs`-indexed structure at a
/// running count of visible rows. That count is the right cursor (a shard the
/// row projection empties contributes none, so skipping it advances by zero),
/// but it silently trusts the source's
/// [`visible_shard_indices`](scx_format_io::ShardSource::visible_shard_indices)
/// plan to agree with the rows actually handed over. A plan that **under**
/// covers places every row after the gap one shard too early and still returns
/// a fully formed result; one that **over** covers indexes past the end — on
/// the CPU a panic, on the GPU an out-of-bounds *device* read, because the
/// kernels index `cell_to_group[global_row + r]` into a buffer of length
/// `n_obs`.
///
/// Both are errors here, in one place, so the CPU and GPU passes cannot drift
/// on which of them checks.
pub(crate) struct VisibleRowCursor {
    pos: usize,
    n_obs: usize,
}

impl VisibleRowCursor {
    pub(crate) fn new(n_obs: usize) -> Self {
        Self { pos: 0, n_obs }
    }

    /// Claim `n_rows` rows for a shard, returning the global visible row its
    /// first row occupies. Errors rather than overflowing the output.
    pub(crate) fn advance(
        &mut self,
        n_rows: usize,
        shard_idx: usize,
        context: &str,
    ) -> Result<usize> {
        self.try_advance(n_rows, shard_idx, context)
            .map_err(AccelError::ShapeError)
    }

    /// Errors unless the shards visited covered exactly `n_obs` rows.
    pub(crate) fn finish(&self, context: &str) -> Result<()> {
        self.try_finish(context).map_err(AccelError::ShapeError)
    }

    /// [`Self::advance`] returning the message rather than an [`AccelError`],
    /// so the GPU passes — whose shard callback is typed on `GpuError` — get the
    /// same arithmetic and the same wording without this module depending on
    /// `scx-gpu`'s error type.
    pub(crate) fn try_advance(
        &mut self,
        n_rows: usize,
        shard_idx: usize,
        context: &str,
    ) -> std::result::Result<usize, String> {
        if self.pos + n_rows > self.n_obs {
            return Err(format!(
                "{context}: shard {shard_idx} has {n_rows} rows, exceeding n_obs = {} at row {}",
                self.n_obs, self.pos
            ));
        }
        let start = self.pos;
        self.pos += n_rows;
        Ok(start)
    }

    /// [`Self::finish`] returning the message; see [`Self::try_advance`].
    pub(crate) fn try_finish(&self, context: &str) -> std::result::Result<(), String> {
        if self.pos != self.n_obs {
            return Err(format!(
                "{context}: the shards visited cover {} rows but the source reports n_obs = {}",
                self.pos, self.n_obs
            ));
        }
        Ok(())
    }
}

pub use pts::{
    group_nonzero_counts_csr, group_nonzero_counts_dense, group_nonzero_counts_streaming,
    GroupNonzeroCounts, PtsFractions,
};

pub use cpu::{
    finalize_pdex, merge_diff_exp_results, pdex_ref, pdex_ref_core, pdex_ref_sparse,
    pdex_ref_streaming, wilcoxon_rank_sum, wilcoxon_rank_sum_sparse, wilcoxon_rank_sum_streaming,
    DiffExpResult, PdexRefResult,
};
// Shared inference helpers reused by the NB-GLM Wald + BH steps (spec §7.7–7.8).
pub(crate) use cpu::{benjamini_hochberg, normal_sf};
#[cfg(feature = "gpu")]
pub use gpu::{
    pdex_ref_gpu, pdex_ref_gpu_dense, wilcoxon_rank_sum_gpu, wilcoxon_rank_sum_gpu_dense,
    GpuDeShardInput,
};

#[cfg(test)]
mod cursor_tests {
    use super::VisibleRowCursor;

    #[test]
    fn a_cursor_hands_out_ascending_offsets_and_accepts_exact_coverage() {
        let mut c = VisibleRowCursor::new(24);
        assert_eq!(c.advance(8, 0, "op").unwrap(), 0);
        assert_eq!(c.advance(8, 1, "op").unwrap(), 8);
        assert_eq!(c.advance(8, 2, "op").unwrap(), 16);
        c.finish("op").unwrap();
    }

    /// A skipped shard advances the cursor by nothing, which is why a running
    /// count stays correct under the row-projection skip.
    #[test]
    fn an_empty_shard_does_not_move_the_cursor() {
        let mut c = VisibleRowCursor::new(8);
        assert_eq!(c.advance(0, 0, "op").unwrap(), 0);
        assert_eq!(c.advance(8, 1, "op").unwrap(), 0);
        c.finish("op").unwrap();
    }

    #[test]
    fn over_coverage_errors_before_the_write_rather_than_indexing_past_the_end() {
        let mut c = VisibleRowCursor::new(8);
        assert_eq!(c.advance(8, 0, "op").unwrap(), 0);
        let err = c.advance(1, 1, "op").unwrap_err().to_string();
        assert!(
            err.contains("shard 1") && err.contains("exceeding n_obs = 8"),
            "{err}"
        );
    }

    #[test]
    fn under_coverage_errors_rather_than_returning_a_shifted_result() {
        let mut c = VisibleRowCursor::new(40);
        c.advance(16, 0, "op").unwrap();
        let err = c.finish("op").unwrap_err().to_string();
        assert!(
            err.contains("cover 16 rows") && err.contains("n_obs = 40"),
            "{err}"
        );
    }
}
