[package]
name = "scx-integration-tests"
version = "0.0.0"
edition = "2021"
publish = false

[dev-dependencies]
scx-format = { path = "../../scx-format", features = ["deletion-vectors"] }
scx-codec = { path = "../../scx-codec" }
scx-ops = { path = "../../scx-ops" }
scx-engine = { path = "../../scx-engine" }
scx-sparse = { path = "../../scx-sparse" }
tempfile = { workspace = true }
arrow = { workspace = true }
