"""Numerical validation of pyscx.accel.harmony_integrate against R harmony.

Each validation dataset is represented by a pair of cached files under
`benchmarks/results/harmony/reference/<name>/`:

  * `inputs.npz`      — `pca` (N x d, f32) + `batch` (N, i32) + `vars_use`.
  * `r_reference.npz` — `Z_corr`, `R`, `Y`, `objective`, `n_iterations`
                         from a fresh R `harmony::RunHarmony` run.

The references are generated by `benchmarks/scripts/generate_harmony_reference.R`
driven by `benchmarks/scripts/build_harmony_validation_fixtures.py`. If
they're missing these tests skip gracefully rather than failing, so the
suite stays green for contributors without access to the validation
datasets.

The original target was:

  * Per-PC Pearson r >= 0.998 vs R reference,
  * Convergence iteration count within ±1 of R,
  * LISI mean within 1% of R `lisi::compute_lisi()`.

The clean-room Rust implementation uses `rand_chacha` (ChaCha8) for
k-means++ seeding and block shuffling, while R harmony uses Mersenne
Twister via `set.seed()`. Identical RNG inputs are impossible without
a shared random stream, and Harmony's stochastic k-means++ init is
sensitive to the first few draws: tail PCs can drift by a few percent
even though the overall embedding structure (and batch-mixing quality)
is preserved. The assertions below therefore use slightly looser
thresholds that still establish *numerical equivalence up to stochastic
noise*:

  * Per-PC Pearson r >= 0.95 per PC and >= 0.97 on the mean (0.998
    would require aligning RNG streams across languages — deferred).
    The test is named for what it enforces (`test_per_pc_pearson_ge_095`);
    it was named `..._ge_0998` while asserting 0.95.
  * Iteration count: REPORTED, not asserted. It carried "within ±6",
    which is vacuous at max_iter=10 — R returns 4/8/5 on these three
    fixtures and SCX can only return 1-10, so every reachable value
    passed. Deleted in Phase 7e; the counts are printed instead.
  * LISI mean within 5% (R `lisi` has its own RNG path through
    `Rtsne::Hbeta`; see benchmarks/results/harmony/REPORT.md for the
    cross-impl LISI table).

Observed mean per-PC r is deliberately NOT quoted here any more. It was
— pbmc_small 0.9992, cell_lines 0.9885, hlca_subset 0.9991 — and those
are pre-M-step numbers on the same gitignored fixtures whose published
form Phase 7e withdrew from `docs/api/python-accel.md`, `docs/scanpy/accel-integration.md`
and `docs/performance/accel-qc-de-integration.md`. Restating them in a test module would make that
withdrawal internally inconsistent. Run with the fixtures present to see
the current values. (Cell-lines remains the worst case: smartseq2 has 47
batches at only ~9.5k cells, amplifying init-seed sensitivity.)
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
REF_ROOT = REPO_ROOT / "benchmarks" / "results" / "harmony" / "reference"

# (name, dataset_file, batch_col, multi_covariate?, n_cap, expected_PC_count)
VALIDATION_SETS = [
    ("pbmc_small", "pbmc3k", None, False, 2700, 30),
    ("cell_lines", "smartseq2", "dataset_id", False, 9478, 20),
    ("hlca_subset", "tabula_sapiens_100k", "donor_id", True, 50_000, 30),
]


def _ref_paths(name: str) -> tuple[Path, Path]:
    d = REF_ROOT / name
    return d / "inputs.npz", d / "r_reference.npz"


def _require_reference(name: str) -> tuple[np.ndarray, np.ndarray, dict]:
    inputs_p, ref_p = _ref_paths(name)
    if not inputs_p.exists() or not ref_p.exists():
        pytest.skip(
            f"missing reference fixture at {inputs_p} / {ref_p}; "
            "run benchmarks/scripts/build_harmony_validation_fixtures.py "
            "(requires R harmony + scanpy + dataset access)."
        )
    inputs = np.load(inputs_p, allow_pickle=True)
    ref = np.load(ref_p)
    pca = inputs["pca"].astype(np.float32)
    batch = inputs["batch"]
    meta = {"params": dict(inputs["params"].item())} if "params" in inputs.files else {"params": {}}
    meta["ref"] = {k: ref[k] for k in ref.files}
    return pca, batch, meta


@pytest.mark.parametrize(
    "name,_dataset,_batch_col,_multi,_n_cap,_n_pcs",
    VALIDATION_SETS,
    ids=[v[0] for v in VALIDATION_SETS],
)
def test_per_pc_pearson_ge_095(
    name, _dataset, _batch_col, _multi, _n_cap, _n_pcs
):
    import pyscx
    import anndata as ad

    pca, batch, meta = _require_reference(name)

    # Build a minimal AnnData wrapper so pyscx.accel.harmony_integrate can
    # read obsm + obs. We don't need the full X matrix.
    labels = [f"b{int(v)}" for v in batch]
    adata = ad.AnnData(
        X=np.zeros((pca.shape[0], 1), dtype=np.float32),
        obs=pd.DataFrame({"batch": pd.Categorical(labels)}),
    )
    adata.obsm["X_pca"] = pca

    params = meta["params"]
    pyscx.accel.harmony_integrate(
        adata,
        "batch",
        n_clusters=int(params.get("nclust", 100)),
        theta=float(params.get("theta", 2.0)),
        max_iter=int(params.get("max_iter", 10)),
        random_state=int(params.get("seed", 0)),
        adjusted_basis="X_pca_harmony",
    )
    got = np.asarray(adata.obsm["X_pca_harmony"], dtype=np.float64)
    ref_z = meta["ref"]["Z_corr"].astype(np.float64)

    assert got.shape == ref_z.shape, (
        f"shape mismatch: got {got.shape}, ref {ref_z.shape}"
    )
    rs = []
    for pc in range(got.shape[1]):
        a = ref_z[:, pc]
        b = got[:, pc]
        if a.std() < 1e-12 and b.std() < 1e-12:
            continue
        r = float(np.corrcoef(a, b)[0, 1])
        rs.append((pc, r))
        assert r >= 0.95, f"{name} PC {pc}: r={r:.4f} < 0.95"

    # The name used to say 0998 while the assertions were 0.95 per PC and 0.97
    # on the mean. Renamed to match what it enforces rather than tightened:
    # SCX seeds k-means++ from `rand_chacha` and R from Mersenne Twister, so
    # the two start from different cluster geometry and a 0.998 bar would be
    # asserting that a stochastic init does not matter.
    mean_r = float(np.mean([r for _, r in rs]))
    assert mean_r >= 0.97, f"{name}: mean per-PC r {mean_r:.4f} < 0.97"

    # The iteration count is REPORTED, not asserted. It used to carry
    # `abs(n_iter_scx - n_iter_ref) <= 6`, which is vacuous at `max_iter=10`:
    # R returns 4 / 8 / 5 on the three fixtures and SCX can only return 1-10,
    # so every reachable value passed. A bar no reachable value can violate is
    # worse than no bar, because it reads as coverage.
    n_iter_ref = int(meta["ref"]["n_iterations"])
    n_iter_scx = int(adata.uns["harmony"]["n_iterations"])
    print(f"{name}: n_iterations scx={n_iter_scx} R={n_iter_ref}")


@pytest.mark.parametrize(
    "name,_dataset,_batch_col,_multi,_n_cap,_n_pcs",
    VALIDATION_SETS,
    ids=[v[0] for v in VALIDATION_SETS],
)
def test_lisi_mean_within_5pct(
    name, _dataset, _batch_col, _multi, _n_cap, _n_pcs
):
    import pyscx
    import anndata as ad

    pca, batch, meta = _require_reference(name)

    # Always compute LISI on the R-corrected embedding so we isolate the
    # LISI routine, not harmony's f32 drift.
    ref_z = meta["ref"]["Z_corr"].astype(np.float32)

    labels = [f"b{int(v)}" for v in batch]
    adata = ad.AnnData(
        X=np.zeros((pca.shape[0], 1), dtype=np.float32),
        obs=pd.DataFrame({"batch": pd.Categorical(labels)}),
    )
    adata.obsm["X_pca_harmony"] = ref_z
    scx_lisi = pyscx.accel.compute_lisi(
        adata, "batch", basis="X_pca_harmony", perplexity=30.0
    )
    scx_mean = float(np.mean(scx_lisi))

    # Compute R LISI on the same inputs via a short Rscript.
    import tempfile
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        emb_p = td / "emb.npy"
        lab_p = td / "lab.npy"
        out_p = td / "lisi.npy"
        np.save(emb_p, ref_z.astype(np.float32))
        np.save(lab_p, np.asarray(batch, dtype=np.int32))
        script = f"""
          library(reticulate); library(lisi)
          np <- import("numpy", convert=TRUE)
          emb <- np$load("{emb_p}"); b <- np$load("{lab_p}")
          meta <- data.frame(batch=as.character(b), stringsAsFactors=FALSE)
          out <- compute_lisi(as.matrix(emb), meta, "batch", perplexity=30)
          np$save("{out_p}", np$asarray(as.numeric(out$batch), dtype="float64"))
        """
        rscript = os.environ.get(
            "RSCRIPT",
            "/home/nickyoungblut/miniforge3/envs/rscx/bin/Rscript",
        )
        subprocess.check_call([rscript, "-e", script])
        r_mean = float(np.mean(np.load(out_p)))

    rel = abs(scx_mean - r_mean) / max(r_mean, 1e-9)
    assert rel < 0.05, (
        f"{name}: LISI mean scx={scx_mean:.4f} R={r_mean:.4f} "
        f"rel diff {rel:.3%} > 5% (see test docstring for rationale)"
    )


def test_lisi_matches_harmonypy_per_cell():
    """Per-cell LISI parity against the harmonypy reference (§2.3 fix).

    The dataset-wide mean test above can hide a systematic per-cell kernel
    error. This asserts SCX's LISI agrees with harmonypy's ``compute_lisi``
    on *every* cell, which only holds once the Gaussian kernel is
    ``exp(-D·beta)`` on the raw (non-squared) neighbour distances — the bug
    fixed in ``scx-accel/src/lisi.rs`` was squaring D a second time.

    harmonypy fits ``3*perplexity`` neighbours (kd-tree) then drops self, so
    it uses ``3*perplexity - 1`` neighbours; we pin ``n_neighbors`` to match.
    """
    harmonypy = pytest.importorskip("harmonypy")
    import pyscx
    import anndata as ad

    rng = np.random.default_rng(0)
    # perplexity is int: harmonypy fits NearestNeighbors(n_neighbors=3*perplexity)
    # and newer sklearn rejects a float n_neighbors.
    n_per, n_dims, n_batches, perplexity = 60, 5, 3, 15
    # Three loosely separated batch blobs so LISI has non-trivial structure.
    centers = rng.normal(scale=4.0, size=(n_batches, n_dims))
    emb = np.vstack(
        [centers[b] + rng.normal(scale=1.0, size=(n_per, n_dims)) for b in range(n_batches)]
    ).astype(np.float32)
    batch = np.concatenate([np.full(n_per, b, dtype=np.int32) for b in range(n_batches)])
    labels = [f"b{int(v)}" for v in batch]

    ref = harmonypy.compute_lisi(
        emb.astype(np.float64),
        pd.DataFrame({"batch": pd.Categorical(labels)}),
        ["batch"],
        perplexity=perplexity,
    )[:, 0]

    adata = ad.AnnData(
        X=np.zeros((emb.shape[0], 1), dtype=np.float32),
        obs=pd.DataFrame({"batch": pd.Categorical(labels)}),
    )
    adata.obsm["X_emb"] = emb
    scx_lisi = np.asarray(
        pyscx.accel.compute_lisi(
            adata,
            "batch",
            basis="X_emb",
            perplexity=perplexity,
            n_neighbors=int(3 * perplexity - 1),
        ),
        dtype=np.float64,
    )

    max_abs = float(np.max(np.abs(scx_lisi - ref)))
    assert max_abs < 1e-2, (
        f"per-cell LISI diverges from harmonypy: max abs diff {max_abs:.4g} "
        f"(scx mean {scx_lisi.mean():.4f} vs ref {ref.mean():.4f})"
    )
