[package]
name = "scx-codec"
version = "0.4.0"
edition = "2021"
description = "Compression codecs for SCX (Rice, FOR-BP, Delta-Golomb)"
license.workspace = true
authors.workspace = true

[dependencies]
byteorder = { workspace = true }
bytemuck = { workspace = true }
half = { workspace = true }
log = { workspace = true }
lz4_flex = { workspace = true }
bitpacking = { workspace = true }
thiserror = { workspace = true }
pco = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "codec_bench"
harness = false
