[package]
name = "scx-sparse"
version = "0.2.0"
edition = "2021"
description = "CSR sparse matrix operations for SCX"
license.workspace = true
authors.workspace = true

[dependencies]
thiserror = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rand_distr = { workspace = true }
log = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
