//! Streaming Pull: download from cloud/local exploded `.scxd` and pack
//! into a local `.scx` file in a single pass.
//!
//! Implements docs/cloud.md (Streaming pull/push).
//!
//! Pipeline:
//!   1. GET `_catalog.bin` + `_header.bin`
//!   2. Parse catalog → know all sections
//!   3. Open output file, write header placeholder
//!   4. Download sections (ordered bounded pipeline) → sequential write
//!   5. Write full catalog + front catalog + root catalog + header
//!   6. fsync + atomic rename

use std::collections::BTreeMap;
use std::io::{BufWriter, Cursor, Read, Seek, SeekFrom, Write};
use std::path::Path;
use std::time::{Duration, Instant, SystemTime};

use futures::stream::StreamExt;

use object_store::path::Path as ObjPath;
use object_store::ObjectStore;

use scx_format_io::catalog::{FullCatalog, FullCatalogEntry, RootCatalog, RootCatalogEntry};
use scx_format_io::header::{FileHeader, HEADER_SIZE};
use scx_format_io::section::{align_to_8, SectionType};

use crate::error::{CloudError, Result};
use crate::explode::section_name_to_path;

/// Offset where sections begin: 256 (header) + 4096 (root catalog placeholder).
const SECTIONS_START_OFFSET: u64 = 4352;

/// Stack-allocated zero buffer for 8-byte alignment padding (max 7 bytes).
const ZEROS: [u8; 8] = [0u8; 8];

/// Age threshold for the old PID-based temp filename (`{stem}.tmp.<pid>`).
/// One hour comfortably exceeds any legitimate in-flight pull whose owning
/// pid we could not confirm via `/proc`.
const STALE_TMP_AGE_OLD: Duration = Duration::from_secs(60 * 60);

/// Age threshold for the new randomized temp filename
/// (`.{stem}_<random>.tmp`). Random suffixes make collisions with a live
/// process impossible by construction, so the mtime check is the only
/// guard against reaping a still-active write. Use 24 h so multi-TB pulls
/// running on slow links are not swept by a concurrent retry.
const STALE_TMP_AGE_NEW: Duration = Duration::from_secs(24 * 60 * 60);

/// Return true if a pid is still live according to `/proc/{pid}` (Linux).
///
/// Non-Linux platforms have no `/proc` — the function returns `false` so
/// the caller falls back to the mtime heuristic. Benchmarks and cloud
/// operations run on Linux, so the proc path is exercised in practice.
fn pid_is_alive(pid: u32) -> bool {
    std::path::Path::new(&format!("/proc/{pid}")).exists()
}

/// Remove orphaned temp files left behind by prior interrupted pulls.
///
/// Two temp-filename schemes coexist:
///   * **Old (pre-PR #74):** `{stem}.tmp.<pid>`. The trailing numeric
///     component is the writer's pid; we use `/proc` liveness as a fast
///     path to skip files whose owner is still running.
///   * **New (PR #74+):** `.{stem}_<random>.tmp`. The random suffix is
///     generated by `tempfile::Builder` and contains no process identity;
///     collisions with a live writer are impossible by construction, so
///     no pid check is possible (or needed).
///
/// A file matching either pattern is deleted iff:
///   1. For the old format only: the trailing pid is not live on `/proc`
///      (or the suffix does not parse as a pid). New-format files skip
///      this check.
///   2. Its mtime is older than the format-specific threshold —
///      `STALE_TMP_AGE_OLD` (1 h) for old, `STALE_TMP_AGE_NEW` (24 h) for
///      new. The new format gets a longer window because the only safety
///      net against reaping an in-flight large pull is the mtime guard.
///
/// Called at the top of both `pull` and `pull_filtered`. Deliberately
/// best-effort: a directory-listing failure is not a pull failure — the
/// worst case is orphans persist; they never block retries.
fn cleanup_stale_tmp_files(dest: &Path) {
    let parent = match dest.parent() {
        Some(p) if !p.as_os_str().is_empty() => p,
        _ => std::path::Path::new("."),
    };
    let stem = match dest.file_name().and_then(|s| s.to_str()) {
        Some(s) => s,
        None => return,
    };
    let old_prefix = format!("{stem}.tmp.");
    let new_prefix = format!(".{stem}_");
    let new_suffix = ".tmp";
    let entries = match std::fs::read_dir(parent) {
        Ok(e) => e,
        Err(_) => return,
    };
    let now = SystemTime::now();
    for entry in entries.flatten() {
        let name = entry.file_name();
        let Some(name_str) = name.to_str() else {
            continue;
        };

        let old_match = name_str.starts_with(&old_prefix);
        let new_match = name_str.starts_with(&new_prefix)
            && name_str.ends_with(new_suffix)
            && name_str.len() > new_prefix.len() + new_suffix.len();
        if !old_match && !new_match {
            continue;
        }

        // Old format only: bail out cheaply if the trailing component
        // parses to a pid that is still alive. New format has no pid.
        if old_match {
            let suffix = &name_str[old_prefix.len()..];
            if let Ok(pid) = suffix.parse::<u32>() {
                if pid_is_alive(pid) {
                    continue;
                }
            }
        }

        // Format-specific mtime threshold. Files younger than the
        // threshold might belong to an active sibling write.
        let threshold = if new_match {
            STALE_TMP_AGE_NEW
        } else {
            STALE_TMP_AGE_OLD
        };
        let Ok(meta) = entry.metadata() else { continue };
        let Ok(mtime) = meta.modified() else { continue };
        let Ok(age) = now.duration_since(mtime) else {
            continue;
        };
        if age < threshold {
            continue;
        }
        let _ = std::fs::remove_file(entry.path());
    }
}

// Cloud read resilience — `RetryConfig`, `is_retryable`, `backoff_delay`, and
// the `RetryingStore` decorator — now lives in `crate::retry`, the single
// timeout/retry implementation installed once at the backend boundary (LC1).
// The decorator (built into the backend by `create_backend`) applies the
// per-request deadline + classified retry/backoff, so the helpers below no
// longer loop: they issue one read through the (already-retrying) store and
// map a terminal `object_store::Error` back into the rich `CloudError`.
pub use crate::retry::RetryConfig;

/// Fetch a whole object through the backend, mapping errors to [`CloudError`].
///
/// Retry/backoff/timeout are applied by the [`crate::retry::RetryingStore`]
/// the backend is wrapped in; this helper only translates a terminal failure
/// (a boxed [`crate::retry::RetryError`]) back into
/// [`CloudError::Timeout`] / [`CloudError::DownloadFailed`].
pub(crate) async fn get_with_retry(
    backend: &dyn ObjectStore,
    path: &ObjPath,
) -> Result<bytes::Bytes> {
    match backend.get(path).await {
        Ok(got) => got.bytes().await.map_err(CloudError::ObjectStore),
        Err(e) => Err(CloudError::from_store_error(e, path)),
    }
}

/// Range-read analogue of [`get_with_retry`], used by the cloud query path
/// (`CloudReader::read_section` / `read_section_for_entry`). Resilience is
/// provided by the wrapped store; this maps terminal errors to [`CloudError`].
pub(crate) async fn get_range_with_retry(
    backend: &dyn ObjectStore,
    path: &ObjPath,
    range: std::ops::Range<u64>,
) -> Result<bytes::Bytes> {
    backend
        .get_range(path, range)
        .await
        .map_err(|e| CloudError::from_store_error(e, path))
}

/// Options for the pull operation.
pub struct PullOptions {
    /// Number of parallel download tasks (default: 8). Downloads run through
    /// an ordered bounded pipeline (`stream::buffered`), so this bounds both
    /// in-flight downloads *and* completed-but-unwritten sections: peak memory
    /// is `parallelism × max_section_size` (LC2).
    pub parallelism: usize,
    /// Produce cloud-ready output with front catalog (default: true).
    pub cloud_ready: bool,
    /// Filter mode for selective pulls (default: `Shard`).
    pub filter_mode: FilterMode,
    /// Per-request retry + timeout policy.
    pub retry_config: RetryConfig,
}

impl Default for PullOptions {
    fn default() -> Self {
        Self {
            parallelism: 8,
            cloud_ready: true,
            filter_mode: FilterMode::default(),
            retry_config: RetryConfig::default(),
        }
    }
}

/// Controls the granularity of the selective pull filter.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum FilterMode {
    /// Shard-granular: download complete shards containing any matching
    /// cell.  The output may include non-matching cells from partially
    /// matching shards.  This is the fast default.
    #[default]
    Shard,
    /// Exact (cell-granular): decode downloaded shards, filter rows,
    /// rebase CSR indptr, and write only matching cells.  Not yet
    /// implemented — reserved for a follow-up patch.
    Exact,
}

/// Statistics from a pull operation.
pub struct PullStats {
    pub bytes_downloaded: u64,
    pub sections_downloaded: usize,
    pub elapsed: std::time::Duration,
    pub throughput_mbps: f64,
}

/// Streaming pull: download an exploded `.scxd` from a source (cloud or local)
/// and pack into a local `.scx` file.
///
/// The source can be a local directory path or a cloud URL pointing to an
/// exploded `.scxd` directory.
pub async fn pull(source: &str, dest: &Path, options: PullOptions) -> Result<PullStats> {
    let start = Instant::now();

    // Sweep any `.tmp.*` orphans left behind by a previously interrupted
    // pull targeting the same destination. Best-effort; a failure here is
    // not a pull failure (see ``cleanup_stale_tmp_files``).
    cleanup_stale_tmp_files(dest);

    // 1. Parse location and create backend
    let location = crate::backend::parse_location(source)?;
    let backend =
        crate::backend::create_backend_with_retry(&location, options.retry_config.clone()).await?;

    // Determine the prefix for object paths
    let prefix = match &location {
        crate::backend::CloudLocation::Gcs { prefix, .. }
        | crate::backend::CloudLocation::S3 { prefix, .. }
        | crate::backend::CloudLocation::Azure { prefix, .. } => prefix.clone(),
        crate::backend::CloudLocation::Local(path) => {
            // For local backend, the backend is rooted at the directory,
            // so we use the directory name as prefix context
            path.file_name()
                .map(|n| n.to_string_lossy().to_string())
                .unwrap_or_default()
        }
    };

    // Helper to build object paths
    let make_path = |filename: &str| -> ObjPath {
        match &location {
            crate::backend::CloudLocation::Local(_) => {
                // Local backend is rooted at the .scxd directory, paths are relative
                ObjPath::from(filename)
            }
            _ => {
                let full = if prefix.ends_with('/') {
                    format!("{prefix}{filename}")
                } else if prefix.is_empty() {
                    filename.to_string()
                } else {
                    format!("{prefix}/{filename}")
                };
                ObjPath::from(full)
            }
        }
    };

    // 2. Download _catalog.bin and _header.bin
    let catalog_path = make_path("_catalog.bin");
    let catalog_data = get_with_retry(backend.as_ref(), &catalog_path).await?;
    let catalog_bytes = catalog_data.to_vec();
    let original_catalog =
        FullCatalog::read_from(&mut Cursor::new(&catalog_bytes), catalog_bytes.len(), true)?;

    let header_path = make_path("_header.bin");
    let header_data = get_with_retry(backend.as_ref(), &header_path).await?;
    let header = FileHeader::read_from(&mut Cursor::new(&header_data))?;

    let mut total_bytes_downloaded = (catalog_bytes.len() + header_data.len()) as u64;

    // 3. Define section ordering for cloud-optimized layout.
    //    `CscShard` placed adjacent to `CsrShard` so column-major
    //    reads stay in the contiguous prefix region of the pulled
    //    file.
    let section_order: &[SectionType] = &[
        SectionType::ObsMetadata,
        SectionType::ObsIndex,
        SectionType::VarMetadata,
        SectionType::VarIndex,
        SectionType::CsrShard,
        SectionType::CscShard,
        SectionType::LayerCsrShard,
        SectionType::ObsmEmbedding,
        SectionType::ObspCsrShard,
        SectionType::UnsBlob,
        SectionType::ObsPredicateIndex,
        SectionType::VarPredicateIndex,
        SectionType::Provenance,
        SectionType::DeletionVectors,
    ];

    // Group and order entries
    let mut grouped: BTreeMap<u8, Vec<&FullCatalogEntry>> = BTreeMap::new();
    for entry in &original_catalog.entries {
        grouped
            .entry(entry.section_type as u8)
            .or_default()
            .push(entry);
    }

    let known_types: std::collections::HashSet<u8> =
        section_order.iter().map(|&st| st as u8).collect();
    let mut ordered_entries: Vec<&FullCatalogEntry> =
        Vec::with_capacity(original_catalog.entries.len());
    for &st in section_order {
        if let Some(entries) = grouped.get(&(st as u8)) {
            ordered_entries.extend(entries);
        }
    }
    // Include any section types not in section_order (unknown/future types)
    for (&group_type, entries) in &grouped {
        if !known_types.contains(&group_type) {
            ordered_entries.extend(entries);
        }
    }

    // 4. Pre-compute the layout from the source catalog.
    //
    //    The whole file is written forward through a `HashingWriter`, so
    //    every offset must be known before the first byte hits disk:
    //    section lengths and checksums are copied verbatim from the source
    //    catalog (today's behaviour — we never recompute either), and the
    //    8-byte alignment between sections is deterministic. This lets the
    //    file checksum be computed incrementally and patched in at the end
    //    without re-reading the entire file.
    let parallelism = options.parallelism.max(1);

    let estimated_front_catalog_size = if options.cloud_ready {
        estimate_catalog_size(ordered_entries.len())
    } else {
        0
    };
    let front_catalog_offset = if options.cloud_ready {
        SECTIONS_START_OFFSET
    } else {
        0
    };
    let prefix_end = if options.cloud_ready {
        // The reserved region is the estimated front catalog size; the
        // alignment-padding bytes that follow are written through the
        // hasher as part of the prefix.
        align_to_8(SECTIONS_START_OFFSET + estimated_front_catalog_size as u64)
    } else {
        SECTIONS_START_OFFSET
    };

    let mut section_offsets: Vec<u64> = Vec::with_capacity(ordered_entries.len());
    let mut cursor = prefix_end;
    let mut modality_table_offset_new: u64 = 0;
    let mut modality_table_length_new: u64 = 0;
    for entry in &ordered_entries {
        cursor = align_to_8(cursor);
        section_offsets.push(cursor);
        if entry.section_type == SectionType::ModalityTable {
            modality_table_offset_new = cursor;
            modality_table_length_new = entry.length;
        }
        cursor += entry.length;
    }
    let full_catalog_offset_new = align_to_8(cursor);

    // 5. Build the new catalog, root catalog, and header — all from
    //    in-memory data only.
    let new_entries: Vec<FullCatalogEntry> = ordered_entries
        .iter()
        .enumerate()
        .map(|(i, entry)| FullCatalogEntry {
            name: entry.name.clone(),
            offset: section_offsets[i],
            length: entry.length,
            section_type: entry.section_type,
            checksum: entry.checksum,
            modality_id: entry.modality_id,
            stats: entry.stats.clone(),
        })
        .collect();

    let new_full_catalog = FullCatalog {
        catalog_version: original_catalog.catalog_version,
        manifest_sequence: original_catalog.manifest_sequence,
        prev_catalog_offset: original_catalog.prev_catalog_offset,
        n_obs: original_catalog.n_obs,
        entries: new_entries,
        // Pull copies sections without changing CSR/CSC content — preserve
        // both generations.
        data_generation: original_catalog.data_generation,
        csc_build_generation: original_catalog.csc_build_generation,
    };
    let mut new_catalog_bytes = Vec::new();
    new_full_catalog.write_to(&mut new_catalog_bytes)?;
    let new_full_catalog_length = new_catalog_bytes.len() as u64;

    let root_catalog = build_root_catalog(&new_full_catalog);
    let mut root_buf = Vec::new();
    root_catalog.write_to(&mut root_buf)?;
    let root_catalog_length = root_buf.len() as u64;
    root_buf.resize(4096, 0);

    let mut new_header = header;
    new_header.root_catalog_offset = HEADER_SIZE as u64;
    new_header.root_catalog_length = root_catalog_length;
    new_header.full_catalog_offset = full_catalog_offset_new;
    new_header.full_catalog_length = new_full_catalog_length;
    // Phase G.1a: pull re-lays out sections, so the source's
    // modality_table_offset is stale. Point at the new location.
    new_header.modality_table_offset = modality_table_offset_new;
    new_header.modality_table_length = modality_table_length_new;
    new_header.file_checksum = 0;

    let front_catalog_fits =
        options.cloud_ready && new_catalog_bytes.len() <= estimated_front_catalog_size;
    if options.cloud_ready {
        if front_catalog_fits {
            new_header.front_catalog_offset = front_catalog_offset;
            new_header.front_catalog_length = new_catalog_bytes.len() as u64;
            new_header.set_front_catalog();
        } else {
            new_header.front_catalog_offset = 0;
            new_header.front_catalog_length = 0;
            new_header.clear_front_catalog();
        }
    }

    let mut header_bytes = Vec::with_capacity(HEADER_SIZE);
    new_header.write_to(&mut header_bytes)?;
    debug_assert_eq!(
        header_bytes.len(),
        HEADER_SIZE,
        "FileHeader must serialize to exactly HEADER_SIZE bytes"
    );

    // 6. Stream the file forward through a HashingWriter.
    //    Order: header → root catalog → front catalog region (cloud_ready)
    //         → sections (downloaded in parallel, written in order)
    //         → full catalog at EOF.
    //    Sections stream in through an ordered bounded pipeline
    //    (`stream::buffered`): downloads run up to `parallelism` at a time and
    //    are yielded in write order, so each is written as it arrives. Peak
    //    memory is bounded by `parallelism × max_section_size` (LC2).
    let (raw_file, tmp_path) = scx_format_io::make_sibling_tempfile(dest)?;
    let mut writer = HashingWriter::new(BufWriter::new(raw_file));

    writer.write_all(&header_bytes)?;
    writer.write_all(&root_buf)?;

    if options.cloud_ready {
        if front_catalog_fits {
            writer.write_all(&new_catalog_bytes)?;
            let remaining = estimated_front_catalog_size - new_catalog_bytes.len();
            if remaining > 0 {
                writer.write_all(&vec![0u8; remaining])?;
            }
        } else {
            writer.write_all(&vec![0u8; estimated_front_catalog_size])?;
        }
        let cur = SECTIONS_START_OFFSET + estimated_front_catalog_size as u64;
        let aligned = align_to_8(cur);
        let pad = (aligned - cur) as usize;
        if pad > 0 {
            writer.write_all(&ZEROS[..pad])?;
        }
    }

    // Build download tasks as (index, filename) pairs.
    let download_tasks: Vec<(usize, String)> = ordered_entries
        .iter()
        .enumerate()
        .map(|(i, entry)| {
            let rel_path = section_name_to_path(&entry.name, entry.section_type).map_err(|e| {
                CloudError::Io(std::io::Error::new(std::io::ErrorKind::InvalidData, e))
            })?;
            Ok((i, rel_path))
        })
        .collect::<Result<Vec<_>>>()?;

    // Ordered bounded pipeline (LC2): `buffered` runs up to `parallelism`
    // downloads concurrently but yields results in input (= write) order, so
    // each section is written as it arrives — no reorder buffer, and peak
    // memory is bounded by `parallelism × max_section_size` as documented.
    let download_stream =
        futures::stream::iter(download_tasks.into_iter().map(|(_idx, filename)| {
            let path = make_path(&filename);
            let backend_ref = &backend;
            async move {
                let result = get_with_retry(backend_ref.as_ref(), &path).await?;
                Ok::<Vec<u8>, CloudError>(result.to_vec())
            }
        }))
        .buffered(parallelism);

    futures::pin_mut!(download_stream);

    let mut write_offset = prefix_end;
    let mut idx: usize = 0;
    while let Some(result) = download_stream.next().await {
        let data = result?;
        let declared = ordered_entries[idx].length;
        if data.len() as u64 != declared {
            return Err(CloudError::InvalidSectionLength {
                name: ordered_entries[idx].name.clone(),
                declared,
                downloaded: data.len() as u64,
            });
        }
        total_bytes_downloaded += data.len() as u64;

        let target_offset = section_offsets[idx];
        let pad = (target_offset - write_offset) as usize;
        if pad > 0 {
            writer.write_all(&ZEROS[..pad])?;
            write_offset = target_offset;
        }
        debug_assert_eq!(write_offset, target_offset);
        writer.write_all(&data)?;
        write_offset += data.len() as u64;
        idx += 1;
    }

    assert_eq!(
        idx,
        ordered_entries.len(),
        "download stream yielded fewer sections than expected"
    );

    // Pad to align with full_catalog_offset_new, then write the full catalog.
    let pad = (full_catalog_offset_new - write_offset) as usize;
    if pad > 0 {
        writer.write_all(&ZEROS[..pad])?;
    }
    writer.write_all(&new_catalog_bytes)?;

    // 7. Finalize hash, patch file_checksum into the header on disk.
    writer.flush()?;
    let (buf_writer, hasher) = writer.into_parts();
    let file_checksum = scx_format_io::checksum::truncate_hash_to_u64(&hasher.finalize());
    let mut file = buf_writer.into_inner().map_err(std::io::Error::from)?;
    new_header.file_checksum = file_checksum;
    file.seek(SeekFrom::Start(0))?;
    new_header.write_to(&mut file)?;

    // 8. fsync + atomic rename.
    file.sync_all()?;
    drop(file);
    tmp_path
        .persist(dest)
        .map_err(|e| CloudError::Io(e.error))?;
    scx_format_io::chmod_to_umask(dest)?;
    scx_format_io::fsync_parent_dir(dest)?;

    let elapsed = start.elapsed();
    let throughput_mbps = if elapsed.as_secs_f64() > 0.0 {
        (total_bytes_downloaded as f64 / 1_000_000.0) / elapsed.as_secs_f64()
    } else {
        0.0
    };

    Ok(PullStats {
        bytes_downloaded: total_bytes_downloaded,
        sections_downloaded: ordered_entries.len(),
        elapsed,
        throughput_mbps,
    })
}

/// Estimate catalog size: 30 bytes header + n_entries × 100 bytes + checksum.
fn estimate_catalog_size(n_entries: usize) -> usize {
    let size = 30 + n_entries * 100 + 32;
    (size + 7) & !7
}

/// Build a root catalog from a full catalog.
fn build_root_catalog(catalog: &FullCatalog) -> RootCatalog {
    let mut groups: BTreeMap<u8, Vec<&FullCatalogEntry>> = BTreeMap::new();
    for entry in &catalog.entries {
        groups
            .entry(entry.section_type as u8)
            .or_default()
            .push(entry);
    }

    let mut root_entries = Vec::new();
    for (&group_type, entries) in &groups {
        let first_offset = entries.iter().map(|e| e.offset).min().unwrap_or(0);
        let total_length: u64 = entries.iter().map(|e| e.length).sum();
        let n_sections = entries.len() as u32;
        root_entries.push(RootCatalogEntry {
            group_type,
            first_section_offset: first_offset,
            total_group_length: total_length,
            n_sections,
            summary: [0u8; 32],
        });
    }

    RootCatalog {
        n_section_groups: root_entries.len() as u16,
        entries: root_entries,
    }
}

/// Compute file checksum: BLAKE3 of entire file, truncated to u64.
///
/// Used only by `pull_filtered`'s legacy write path (re-reads the file
/// after writing). `pull()` uses [`HashingWriter`] to hash incrementally
/// during the forward write and avoids the re-read entirely.
fn compute_file_checksum(file: &mut (impl Read + Seek)) -> Result<u64> {
    file.seek(SeekFrom::Start(0))?;
    let mut hasher = blake3::Hasher::new();
    let mut chunk = [0u8; 65536];
    loop {
        let n = file.read(&mut chunk)?;
        if n == 0 {
            break;
        }
        hasher.update(&chunk[..n]);
    }
    let hash = hasher.finalize();
    Ok(scx_format_io::checksum::truncate_hash_to_u64(&hash))
}

/// `Write` adapter that incrementally feeds every byte written to it
/// through a BLAKE3 hasher.
///
/// Used by `pull()` to compute the file checksum as the output is
/// streamed forward, avoiding a multi-GB re-read after the writes
/// complete. The hash assumes a single forward pass (no `Seek`), which
/// is the contract the restructured `pull()` honors.
struct HashingWriter<W: Write> {
    inner: W,
    hasher: blake3::Hasher,
}

impl<W: Write> HashingWriter<W> {
    fn new(inner: W) -> Self {
        Self {
            inner,
            hasher: blake3::Hasher::new(),
        }
    }

    fn into_parts(self) -> (W, blake3::Hasher) {
        (self.inner, self.hasher)
    }
}

impl<W: Write> Write for HashingWriter<W> {
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        let n = self.inner.write(buf)?;
        self.hasher.update(&buf[..n]);
        Ok(n)
    }

    fn flush(&mut self) -> std::io::Result<()> {
        self.inner.flush()
    }

    fn write_all(&mut self, buf: &[u8]) -> std::io::Result<()> {
        self.inner.write_all(buf)?;
        self.hasher.update(buf);
        Ok(())
    }
}

/// Statistics from a selective pull operation.
#[derive(Debug)]
pub struct PullFilteredStats {
    pub total_shards: usize,
    pub downloaded_shards: usize,
    pub skipped_shards: usize,
    pub matching_cells: u64,
    pub bytes_downloaded: u64,
    pub bytes_saved: u64,
    pub elapsed: std::time::Duration,
    /// Section types present in the source but omitted from the
    /// selective pull output (e.g., ObsmEmbedding, LayerCsrShard).
    pub omitted_section_types: Vec<SectionType>,
    /// The filter mode used for this pull.
    pub filter_mode: FilterMode,
}

/// Selective pull: download only shards matching a predicate.
///
/// Pipeline:
///   1. GET `_catalog.bin` → parse catalog, identify shard row ranges
///   2. GET `obs.arrow` → evaluate predicate against obs metadata
///   3. Map matching cells to shard IDs (from catalog row ranges)
///   4. GET only matching shards (parallel) + var.arrow + other non-shard sections
///   5. Write filtered obs (only matching rows) + matching shards
///   6. Write catalog + header → fsync → rename
pub async fn pull_filtered(
    source: &str,
    dest: &Path,
    filter: &str,
    options: PullOptions,
) -> Result<PullFilteredStats> {
    let start = Instant::now();

    // Exact cell-granular mode is reserved for a follow-up patch.
    if options.filter_mode == FilterMode::Exact {
        return Err(CloudError::Io(std::io::Error::new(
            std::io::ErrorKind::Unsupported,
            "exact cell-granular filter mode is not yet implemented; \
             use filter_mode='shard' (the default) for shard-granular pulls",
        )));
    }

    // Same orphan-sweep as `pull`: any `.tmp.{pid}` files left by a
    // prior interrupted run are removed before we start downloading.
    cleanup_stale_tmp_files(dest);

    // 1. Parse location and create backend
    let location = crate::backend::parse_location(source)?;
    let backend =
        crate::backend::create_backend_with_retry(&location, options.retry_config.clone()).await?;

    let make_path = build_path_fn(&location);

    // 2. Download _catalog.bin and _header.bin
    let catalog_path = make_path("_catalog.bin");
    let catalog_data = get_with_retry(backend.as_ref(), &catalog_path).await?;
    let catalog_bytes = catalog_data.to_vec();
    let original_catalog =
        FullCatalog::read_from(&mut Cursor::new(&catalog_bytes), catalog_bytes.len(), true)?;

    let header_path = make_path("_header.bin");
    let header_data = get_with_retry(backend.as_ref(), &header_path).await?;
    let header = FileHeader::read_from(&mut Cursor::new(&header_data))?;

    let mut total_bytes_downloaded = (catalog_bytes.len() + header_data.len()) as u64;

    // 3. Download obs.arrow and evaluate predicate
    let obs_path_str = section_name_to_path("obs", SectionType::ObsMetadata)
        .map_err(|e| CloudError::Io(std::io::Error::new(std::io::ErrorKind::InvalidData, e)))?;
    let obs_obj_path = make_path(&obs_path_str);
    let obs_data = get_with_retry(backend.as_ref(), &obs_obj_path).await?;
    total_bytes_downloaded += obs_data.len() as u64;
    let obs_bytes = obs_data.to_vec();

    // Parse obs as Arrow IPC. Downcast `LargeUtf8 → Utf8` (and binary)
    // so the predicate evaluator and downstream pyscx callers see the
    // canonical narrow types regardless of the on-disk encoding.
    let obs_cursor = Cursor::new(&obs_bytes);
    let obs_reader = arrow::ipc::reader::FileReader::try_new(obs_cursor, None)
        .map_err(|e| CloudError::Io(std::io::Error::new(std::io::ErrorKind::InvalidData, e)))?;
    let raw_batch: arrow::array::RecordBatch = obs_reader
        .into_iter()
        .next()
        .ok_or_else(|| {
            CloudError::Io(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "obs Arrow IPC file contains no batches",
            ))
        })?
        .map_err(|e| CloudError::Io(std::io::Error::new(std::io::ErrorKind::InvalidData, e)))?;
    let obs_batch = scx_format_io::downcast_large_types(&raw_batch)?;
    let obs_schema = obs_batch.schema();

    // Parse and evaluate predicate
    let predicate = scx_engine::parse_predicate(filter, &obs_schema, "obs").map_err(|e| {
        CloudError::Io(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            format!("predicate parse error: {e}"),
        ))
    })?;
    let mask = scx_engine::evaluate(&predicate, &obs_batch).map_err(|e| {
        CloudError::Io(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!("predicate evaluation error: {e}"),
        ))
    })?;

    // Collect matching row indices (used to identify needed shards)
    let matching_rows: Vec<u64> = (0..mask.len())
        .filter(|&i| mask.value(i))
        .map(|i| i as u64)
        .collect();
    let matching_cells = matching_rows.len() as u64;

    // 4. Map matching rows to shard IDs
    let sorted_shards = original_catalog.shards_sorted();
    let total_shards = sorted_shards.len();

    let mut needed_shard_indices: std::collections::BTreeSet<usize> =
        std::collections::BTreeSet::new();

    for &row_idx in &matching_rows {
        for (shard_idx, entry) in sorted_shards.iter().enumerate() {
            if let Some(stats) = &entry.stats {
                if row_idx >= stats.row_start && row_idx < stats.row_end {
                    needed_shard_indices.insert(shard_idx);
                    break;
                }
            }
        }
    }

    let downloaded_shards = needed_shard_indices.len();
    let skipped_shards = total_shards - downloaded_shards;

    // Collect ALL row indices from downloaded shards (not just predicate-matching
    // rows). Shards are copied verbatim so the output file must include obs rows
    // for every row in those shards, otherwise n_obs disagrees with shard data.
    let shard_row_indices: Vec<u64> = needed_shard_indices
        .iter()
        .flat_map(|&si| {
            if let Some(stats) = &sorted_shards[si].stats {
                (stats.row_start..stats.row_end).collect::<Vec<u64>>()
            } else {
                vec![]
            }
        })
        .collect();
    let shard_total_rows = shard_row_indices.len() as u64;

    // Calculate bytes saved (estimate from skipped shards)
    let bytes_saved: u64 = sorted_shards
        .iter()
        .enumerate()
        .filter(|(i, _)| !needed_shard_indices.contains(i))
        .map(|(_, e)| e.length)
        .sum();

    // 5. Determine which sections to download; collect omitted types.
    let mut entries_to_download: Vec<&FullCatalogEntry> = Vec::new();
    let mut shard_name_set: std::collections::HashSet<String> = std::collections::HashSet::new();
    let mut omitted_types_set: std::collections::BTreeSet<u8> = std::collections::BTreeSet::new();

    for &si in &needed_shard_indices {
        shard_name_set.insert(sorted_shards[si].name.clone());
    }

    for entry in &original_catalog.entries {
        match entry.section_type {
            SectionType::ObsMetadata => continue, // already downloaded
            SectionType::CsrShard if shard_name_set.contains(&entry.name) => {
                entries_to_download.push(entry);
            }
            SectionType::VarMetadata | SectionType::VarIndex | SectionType::UnsBlob => {
                entries_to_download.push(entry);
            }
            // Phase G.1c: pull the modality table so we can re-emit
            // it in the local file with rewritten per-modality counts.
            SectionType::ModalityTable => {
                entries_to_download.push(entry);
            }
            other => {
                // Track omitted section types (obsm, layers, obsp, etc.).
                // Skip ObsIndex since obs is already special-cased above;
                // skip CsrShard since non-matching shards are tracked in
                // `skipped_shards`, not `omitted_section_types`.
                if other != SectionType::ObsIndex && other != SectionType::CsrShard {
                    omitted_types_set.insert(other as u8);
                }
            }
        }
    }

    let omitted_section_types: Vec<SectionType> = omitted_types_set
        .iter()
        .filter_map(|&v| SectionType::from_u8(v))
        .collect();

    // Sort entries into write order for streaming. ModalityTable is
    // separated for post-stream rewriting (it depends on the final
    // catalog entries). The write order matches the section_write_order
    // used by pull(): var → csr shards → uns.
    let type_priority = |st: SectionType| -> u8 {
        match st {
            SectionType::VarMetadata => 0,
            SectionType::VarIndex => 1,
            SectionType::CsrShard => 2,
            SectionType::UnsBlob => 3,
            _ => 4,
        }
    };

    let mut streamable_entries: Vec<&FullCatalogEntry> = Vec::new();
    let mut modality_entry: Option<&FullCatalogEntry> = None;
    for entry in &entries_to_download {
        if entry.section_type == SectionType::ModalityTable {
            modality_entry = Some(entry);
        } else {
            streamable_entries.push(entry);
        }
    }
    streamable_entries.sort_by_key(|e| type_priority(e.section_type));

    // Download the modality table separately — it is tiny and requires
    // post-processing based on the final catalog entries.
    let modality_table_bytes = if let Some(mt_entry) = modality_entry {
        let rel_path = section_name_to_path(&mt_entry.name, mt_entry.section_type)
            .map_err(|e| CloudError::Io(std::io::Error::new(std::io::ErrorKind::InvalidData, e)))?;
        let path = make_path(&rel_path);
        let data = get_with_retry(backend.as_ref(), &path).await?;
        total_bytes_downloaded += data.len() as u64;
        Some(data.to_vec())
    } else {
        None
    };

    // 6. Build obs for all rows in downloaded shards (not just predicate-matching
    //    rows) so that obs row count matches shard data.
    let filtered_obs = filter_record_batch(&obs_batch, &shard_row_indices)?;
    let filtered_obs_bytes = record_batch_to_arrow_ipc(&filtered_obs)?;

    // 7. Write packed output — sections stream to disk as they arrive
    //    in write order, so peak memory is bounded by
    //    `parallelism × max_section_size`.
    let parallelism = options.parallelism.max(1);
    // Collision-safe sibling temp file.
    let (raw_file, tmp_path) = scx_format_io::make_sibling_tempfile(dest)?;
    let mut writer = BufWriter::new(raw_file);

    writer.write_all(&vec![0u8; SECTIONS_START_OFFSET as usize])?;
    let mut write_offset = SECTIONS_START_OFFSET;

    let mut new_entries: Vec<FullCatalogEntry> = Vec::new();

    // Write filtered obs first
    {
        let aligned = align_to_8(write_offset);
        let pad = (aligned - write_offset) as usize;
        if pad > 0 {
            writer.write_all(&ZEROS[..pad])?;
            write_offset = aligned;
        }
        let obs_checksum = blake3::hash(&filtered_obs_bytes);
        writer.write_all(&filtered_obs_bytes)?;
        new_entries.push(FullCatalogEntry {
            name: "obs".to_string(),
            offset: write_offset,
            length: filtered_obs_bytes.len() as u64,
            section_type: SectionType::ObsMetadata,
            checksum: *obs_checksum.as_bytes(),
            modality_id: 0,
            stats: None,
        });
        write_offset += filtered_obs_bytes.len() as u64;
    }

    // 8. Stream section downloads through an ordered bounded pipeline (LC2):
    //    `buffered` caps concurrency at `parallelism` while yielding results in
    //    write order, so each section is written as it arrives — no reorder
    //    buffer, peak memory bounded by `parallelism × max_section_size`.
    let download_tasks: Vec<(usize, String)> = streamable_entries
        .iter()
        .enumerate()
        .map(|(i, entry)| {
            let rel_path = section_name_to_path(&entry.name, entry.section_type).map_err(|e| {
                CloudError::Io(std::io::Error::new(std::io::ErrorKind::InvalidData, e))
            })?;
            Ok((i, rel_path))
        })
        .collect::<Result<Vec<_>>>()?;

    let filtered_dl_stream =
        futures::stream::iter(download_tasks.into_iter().map(|(_idx, filename)| {
            let path = make_path(&filename);
            let backend_ref = &backend;
            async move {
                let result = get_with_retry(backend_ref.as_ref(), &path).await?;
                Ok::<Vec<u8>, CloudError>(result.to_vec())
            }
        }))
        .buffered(parallelism);

    futures::pin_mut!(filtered_dl_stream);

    let mut new_row_offset: u64 = 0;
    let mut idx: usize = 0;

    while let Some(result) = filtered_dl_stream.next().await {
        let section_data = result?;
        total_bytes_downloaded += section_data.len() as u64;
        let entry = streamable_entries[idx];

        // Pad to 8-byte alignment
        let aligned = align_to_8(write_offset);
        let pad = (aligned - write_offset) as usize;
        if pad > 0 {
            writer.write_all(&ZEROS[..pad])?;
            write_offset = aligned;
        }

        let new_offset = write_offset;
        writer.write_all(&section_data)?;
        write_offset += section_data.len() as u64;

        let new_stats = if entry.section_type == SectionType::CsrShard {
            if let Some(old_stats) = &entry.stats {
                let shard_rows = old_stats.row_end - old_stats.row_start;
                let ns = scx_format_io::catalog::ShardStats {
                    row_start: new_row_offset,
                    row_end: new_row_offset + shard_rows,
                    col_start: old_stats.col_start,
                    col_end: old_stats.col_end,
                    nnz: old_stats.nnz,
                    value_min: old_stats.value_min,
                    value_max: old_stats.value_max,
                    value_sum: old_stats.value_sum,
                    n_indexed_columns: old_stats.n_indexed_columns,
                    column_stats: old_stats.column_stats.clone(),
                };
                new_row_offset += shard_rows;
                Some(ns)
            } else {
                entry.stats.clone()
            }
        } else {
            entry.stats.clone()
        };

        new_entries.push(FullCatalogEntry {
            name: entry.name.clone(),
            offset: new_offset,
            length: section_data.len() as u64,
            section_type: entry.section_type,
            checksum: entry.checksum,
            modality_id: entry.modality_id,
            stats: new_stats,
        });

        idx += 1;
    }

    // Sanity: all streamable sections must have been written.
    assert_eq!(
        idx,
        streamable_entries.len(),
        "filtered download stream yielded fewer sections than expected"
    );

    // Phase G.1c: re-emit the ModalityTable section at EOF before
    // the catalog. Per-modality `n_csr_shards` and `nnz` are
    // recomputed from the filtered new_entries; modalities that
    // were entirely filtered out keep their entry with
    // n_csr_shards=0/nnz=0 so the modality table's structure
    // (names, types, n_vars) survives the filter unchanged.
    let (modality_table_offset_new, modality_table_length_new) = if header.n_modalities > 0 {
        if let Some(mt_bytes) = &modality_table_bytes {
            let mut table = scx_format_io::ModalityTable::read_from(
                &mut Cursor::new(mt_bytes),
                mt_bytes.len(),
            )?;
            // Reset per-modality counts before recomputing from
            // the filtered catalog. CSC sidecars are dropped
            // file-wide on pull_filtered (matching the
            // header.clear_csc() / n_csc_shards = 0 below); zero
            // each modality's CSC marker too.
            for info in table.entries.iter_mut() {
                info.n_csr_shards = 0;
                info.n_csc_shards = 0;
                info.nnz = 0;
                info.flags = scx_format_io::ModalityFlags::from_bits_truncate(
                    info.flags.bits() & !scx_format_io::ModalityFlags::HAS_CSC,
                );
            }
            for entry in &new_entries {
                if entry.modality_id == 0 {
                    continue;
                }
                let idx = (entry.modality_id - 1) as usize;
                if let Some(info) = table.entries.get_mut(idx) {
                    if entry.section_type == SectionType::CsrShard {
                        info.n_csr_shards += 1;
                        if let Some(stats) = &entry.stats {
                            info.nnz += stats.nnz;
                        }
                    }
                }
            }
            let mt_aligned = align_to_8(write_offset);
            let pad = (mt_aligned - write_offset) as usize;
            if pad > 0 {
                writer.write_all(&ZEROS[..pad])?;
                write_offset = mt_aligned;
            }
            let mt_offset_new = write_offset;
            let mut mt_buf = Vec::new();
            table.write_to(&mut mt_buf)?;
            let mt_checksum = blake3::hash(&mt_buf);
            writer.write_all(&mt_buf)?;
            let mt_len = mt_buf.len() as u64;
            write_offset += mt_len;
            new_entries.push(FullCatalogEntry {
                name: "modality_table".to_string(),
                offset: mt_offset_new,
                length: mt_len,
                section_type: SectionType::ModalityTable,
                checksum: *mt_checksum.as_bytes(),
                modality_id: 0,
                stats: None,
            });
            (mt_offset_new, mt_len)
        } else {
            (0u64, 0u64)
        }
    } else {
        (0u64, 0u64)
    };

    // Write full catalog at EOF
    let catalog_aligned = align_to_8(write_offset);
    let pad = (catalog_aligned - write_offset) as usize;
    if pad > 0 {
        writer.write_all(&ZEROS[..pad])?;
    }
    let full_catalog_offset_new = catalog_aligned;

    let new_full_catalog = FullCatalog {
        catalog_version: original_catalog.catalog_version,
        manifest_sequence: original_catalog.manifest_sequence + 1,
        prev_catalog_offset: 0,
        n_obs: shard_total_rows,
        entries: new_entries,
        // Filtered pull changes the row set and drops CSC file-wide, so
        // bump the data generation; the output emits no CSC sidecar.
        data_generation: original_catalog.data_generation + 1,
        csc_build_generation: 0,
    };
    let mut new_catalog_bytes = Vec::new();
    new_full_catalog.write_to(&mut new_catalog_bytes)?;
    let new_full_catalog_length = new_catalog_bytes.len() as u64;
    writer.write_all(&new_catalog_bytes)?;

    // Build and write root catalog
    let root_catalog = build_root_catalog(&new_full_catalog);
    let mut root_buf = Vec::new();
    root_catalog.write_to(&mut root_buf)?;
    let root_catalog_length = root_buf.len() as u64;
    root_buf.resize(4096, 0);
    writer.seek(SeekFrom::Start(HEADER_SIZE as u64))?;
    writer.write_all(&root_buf)?;

    // Write header
    let mut new_header = header;
    new_header.n_obs = shard_total_rows;
    // Recompute shard counts, nnz, and has_* flags from the retained
    // catalog entries. Selective pull is shard-granular (whole shards are
    // kept), so each retained shard's stats.nnz is already correct and the
    // sum is the true subset nnz. This subsumes the manual n_csr_shards /
    // n_csc_shards / clear_csc bookkeeping below and, crucially, replaces
    // the stale full-source `nnz` that `header` carried in (otherwise
    // `scx info` reports the full dataset's nnz on a pulled subset).
    // pull_filtered drops CSC sidecars (the catalog filter loop excludes
    // CscShard entries), so sync correctly reports n_csc_shards = 0 and
    // clears the CSC flag.
    new_header.sync_from_catalog(&new_full_catalog);
    // Phase G.1c: point at the rewritten modality table (or zero if
    // the source had no modality table).
    new_header.modality_table_offset = modality_table_offset_new;
    new_header.modality_table_length = modality_table_length_new;
    new_header.root_catalog_offset = HEADER_SIZE as u64;
    new_header.root_catalog_length = root_catalog_length;
    new_header.full_catalog_offset = full_catalog_offset_new;
    new_header.full_catalog_length = new_full_catalog_length;
    new_header.front_catalog_offset = 0;
    new_header.front_catalog_length = 0;
    new_header.clear_front_catalog();
    new_header.file_checksum = 0;

    writer.seek(SeekFrom::Start(0))?;
    new_header.write_to(&mut writer)?;

    // `pull()` was restructured to hash incrementally during the forward
    // write; `pull_filtered` still uses the legacy re-read path. Selective
    // pulls download a subset of shards (typically <10% of cells), so the
    // re-read is usually <100 MB and not on the critical path. The
    // restructure is feasible — obs is rewritten in-memory before the
    // stream, and the rewritten modality table content can be derived
    // upfront from `needed_shard_indices` rather than from streamed
    // `new_entries` — but is deferred so this patch stays focused on the
    // multi-GB `pull()` case the review flagged.
    writer.flush()?;
    let mut file = writer.into_inner().map_err(std::io::Error::from)?;
    let file_checksum = compute_file_checksum(&mut file)?;
    new_header.file_checksum = file_checksum;
    file.seek(SeekFrom::Start(0))?;
    new_header.write_to(&mut file)?;

    file.sync_all()?;
    drop(file);
    tmp_path
        .persist(dest)
        .map_err(|e| CloudError::Io(e.error))?;
    scx_format_io::chmod_to_umask(dest)?;
    scx_format_io::fsync_parent_dir(dest)?;

    let elapsed = start.elapsed();

    Ok(PullFilteredStats {
        total_shards,
        downloaded_shards,
        skipped_shards,
        matching_cells,
        bytes_downloaded: total_bytes_downloaded,
        bytes_saved,
        elapsed,
        omitted_section_types,
        filter_mode: options.filter_mode,
    })
}

/// Build a path-constructing closure from a parsed location.
pub(crate) fn build_path_fn(
    location: &crate::backend::CloudLocation,
) -> Box<dyn Fn(&str) -> ObjPath + '_> {
    match location {
        crate::backend::CloudLocation::Local(_) => {
            Box::new(|filename: &str| ObjPath::from(filename))
        }
        crate::backend::CloudLocation::Gcs { prefix, .. }
        | crate::backend::CloudLocation::S3 { prefix, .. }
        | crate::backend::CloudLocation::Azure { prefix, .. } => {
            let prefix = prefix.clone();
            Box::new(move |filename: &str| {
                let full = if prefix.ends_with('/') {
                    format!("{prefix}{filename}")
                } else if prefix.is_empty() {
                    filename.to_string()
                } else {
                    format!("{prefix}/{filename}")
                };
                ObjPath::from(full)
            })
        }
    }
}

/// Filter a RecordBatch to only include rows at the given indices.
fn filter_record_batch(
    batch: &arrow::array::RecordBatch,
    row_indices: &[u64],
) -> Result<arrow::array::RecordBatch> {
    use arrow::array::UInt64Array;
    let indices = UInt64Array::from(row_indices.to_vec());
    let columns: Vec<arrow::array::ArrayRef> = batch
        .columns()
        .iter()
        .map(|col| arrow::compute::take(col.as_ref(), &indices, None))
        .collect::<std::result::Result<Vec<_>, _>>()
        .map_err(|e| CloudError::Io(std::io::Error::new(std::io::ErrorKind::InvalidData, e)))?;
    let filtered = arrow::array::RecordBatch::try_new(batch.schema(), columns)
        .map_err(|e| CloudError::Io(std::io::Error::new(std::io::ErrorKind::InvalidData, e)))?;
    Ok(filtered)
}

/// Serialize a RecordBatch to Arrow IPC bytes (File format).
///
/// Upcasts `Utf8 → LargeUtf8` so columns larger than 2 GB do not
/// overflow Arrow IPC's 32-bit offset limit (see
/// [`scx_format_io::arrow_compat`]).
fn record_batch_to_arrow_ipc(batch: &arrow::array::RecordBatch) -> Result<Vec<u8>> {
    let batch = scx_format_io::upcast_to_large_types(batch)?;
    let mut buf = Vec::new();
    {
        let mut ipc_writer = arrow::ipc::writer::FileWriter::try_new(&mut buf, &batch.schema())
            .map_err(|e| CloudError::Io(std::io::Error::new(std::io::ErrorKind::InvalidData, e)))?;
        ipc_writer
            .write(&batch)
            .map_err(|e| CloudError::Io(std::io::Error::new(std::io::ErrorKind::InvalidData, e)))?;
        ipc_writer
            .finish()
            .map_err(|e| CloudError::Io(std::io::Error::new(std::io::ErrorKind::InvalidData, e)))?;
    }
    Ok(buf)
}

#[cfg(test)]
#[path = "pull_tests.rs"]
mod tests;
