[package]
name = "scx-format-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
scx-format = { path = ".." }

[[bin]]
name = "fuzz_header"
path = "fuzz_targets/fuzz_header.rs"
test = false
doc = false

[[bin]]
name = "fuzz_shard"
path = "fuzz_targets/fuzz_shard.rs"
test = false
doc = false
