[package]
name = "scx-mtx"
version = "0.4.4"
edition = "2021"
description = "Matrix Market (MTX) I/O for SCX: read/write Cell Ranger MTX directories"
license.workspace = true
authors.workspace = true

[dependencies]
arrow = { workspace = true }
flate2 = "1"
serde_json = { workspace = true }
thiserror = { workspace = true }
scx-format = { path = "../scx-format" }
scx-codec = { path = "../scx-codec" }

[dev-dependencies]
tempfile = { workspace = true }
scx-sparse = { path = "../scx-sparse" }
