//! Write SCX data to Cell Ranger–style MTX directories.
//!
//! Output is always gzip-compressed:
//! - `matrix.mtx.gz`
//! - `barcodes.tsv.gz`
//! - `features.tsv.gz`

use std::io::{BufWriter, Write};
use std::path::Path;

use arrow::array::{Array, AsArray};
use flate2::write::GzEncoder;
use flate2::Compression;

use scx_format_io::reader::ScxReader;

use crate::error::MtxError;

/// Write an SCX file to a Cell Ranger–style MTX directory.
///
/// Creates `output_dir` if it doesn't exist, then writes:
/// - `matrix.mtx.gz` — sparse matrix in COO format
/// - `barcodes.tsv.gz` — cell barcodes
/// - `features.tsv.gz` — gene/feature metadata
///
/// Logically deleted cells are **excluded**. MatrixMarket has no notion of a
/// deletion vector, so unlike an SCX→SCX rewrite there is nothing to carry the
/// deletion in — the only faithful export is one that leaves the rows out. X and
/// obs are filtered by the same mask and must stay that way: `barcodes.tsv.gz`
/// with more lines than the matrix has columns is a directory Cell Ranger and
/// Scanpy both reject.
pub fn write_scx_to_mtx(scx_path: &Path, output_dir: &Path) -> Result<(), MtxError> {
    std::fs::create_dir_all(output_dir)?;

    let reader = ScxReader::open(scx_path)?;
    let csr = reader.read_all_csr_shards_filtered()?;
    let n_obs = csr.shape.0;
    let n_vars = csr.shape.1;
    let nnz = csr.nnz();

    // Write matrix.mtx.gz
    write_matrix_mtx(
        output_dir,
        &csr.indptr,
        &csr.indices,
        &csr.data,
        n_obs,
        n_vars,
        nnz,
    )?;

    // Write barcodes.tsv.gz. Synthetic barcodes are a fallback for *genuinely
    // absent* obs only; a decode/checksum failure is corruption and must abort
    // rather than silently emit fabricated `cell_i` IDs (SCX-009).
    match reader.read_obs_filtered() {
        Ok(obs) => write_barcodes_tsv(output_dir, &obs)?,
        Err(scx_format_io::error::ScxError::SectionNotFound(_)) => {
            write_synthetic_barcodes(output_dir, n_obs)?;
        }
        Err(e) => return Err(e.into()),
    }

    // Write features.tsv.gz (same absence-vs-corruption rule as obs).
    match reader.read_var() {
        Ok(var) => write_features_tsv(output_dir, &var)?,
        Err(scx_format_io::error::ScxError::SectionNotFound(_)) => {
            write_synthetic_features(output_dir, n_vars)?;
        }
        Err(e) => return Err(e.into()),
    }

    Ok(())
}

/// Write `matrix.mtx.gz` in COO format.
fn write_matrix_mtx(
    dir: &Path,
    indptr: &[i64],
    indices: &[i32],
    data: &[f32],
    n_rows: usize,
    n_cols: usize,
    nnz: usize,
) -> Result<(), MtxError> {
    let path = dir.join("matrix.mtx.gz");
    let file = std::fs::File::create(&path)?;
    let gz = GzEncoder::new(file, Compression::default());
    let mut w = BufWriter::new(gz);

    // Header
    // Detect if all values are integers for the header type field
    let all_integer = data
        .iter()
        .all(|&v| v == v.floor() && v.is_finite() && v >= 0.0);
    let type_str = if all_integer { "integer" } else { "real" };

    // CLI8: derive the declared nnz from the CSR indptr so the header always
    // matches the body, which emits exactly `indptr[r+1]-indptr[r]` lines per
    // row. Trusting the caller's `nnz` produces a file whose declared count
    // diverges from the body if `nnz` is stale or the CSR carries explicit
    // zeros/dups (rejected by strict readers).
    let body_nnz = if indptr.len() > n_rows {
        indptr[n_rows].saturating_sub(indptr[0]).max(0) as usize
    } else {
        nnz
    };
    debug_assert_eq!(
        body_nnz, nnz,
        "MTX writer: caller-supplied nnz disagrees with indptr-derived nnz"
    );

    writeln!(w, "%%MatrixMarket matrix coordinate {} general", type_str)?;
    writeln!(w, "% Generated by scx-mtx from SCX format")?;
    // SCX stores cells × genes (obs × var), but 10x/Cell Ranger Matrix Market
    // is features × barcodes (genes × cells). Transpose on export (SCX-010):
    // the size line is `n_vars n_obs nnz` and each triplet is emitted as
    // `col(gene) row(cell) value`. Iterating the CSR in cell (obs) order means
    // entries come out grouped by column (barcode) and ascending within a
    // column by row (feature) — exactly Cell Ranger's column-major layout.
    writeln!(w, "{} {} {}", n_cols, n_rows, body_nnz)?;

    // Write COO triplets (1-indexed), transposed to features × barcodes.
    for row in 0..n_rows {
        let start = indptr[row] as usize;
        let end = indptr[row + 1] as usize;
        for idx in start..end {
            let col = indices[idx];
            let val = data[idx];
            if all_integer {
                // Write as integer to avoid unnecessary decimal points
                writeln!(w, "{} {} {}", col + 1, row + 1, val as i64)?;
            } else {
                writeln!(w, "{} {} {}", col + 1, row + 1, val)?;
            }
        }
    }

    w.flush()?;
    Ok(())
}

/// Write `barcodes.tsv.gz` from obs RecordBatch.
fn write_barcodes_tsv(dir: &Path, obs: &arrow::array::RecordBatch) -> Result<(), MtxError> {
    let path = dir.join("barcodes.tsv.gz");
    let file = std::fs::File::create(&path)?;
    let gz = GzEncoder::new(file, Compression::default());
    let mut w = BufWriter::new(gz);

    // Use the first column as barcode (typically "_index" or "barcode")
    if obs.num_columns() == 0 || obs.num_rows() == 0 {
        return Ok(());
    }

    let col = obs.column(0);
    if let Some(string_arr) = col.as_any().downcast_ref::<arrow::array::StringArray>() {
        for i in 0..string_arr.len() {
            writeln!(w, "{}", string_arr.value(i))?;
        }
    } else if let Some(dict_arr) = col
        .as_any()
        .downcast_ref::<arrow::array::DictionaryArray<arrow::datatypes::Int32Type>>()
    {
        let values = dict_arr.values().as_string::<i32>();
        for i in 0..dict_arr.len() {
            // CLI5: a null dictionary key must still emit a line, or every
            // subsequent positional barcode shifts up by one row. Use a
            // synthesized placeholder matching the non-dictionary fallback.
            match dict_arr.key(i) {
                Some(key) => writeln!(w, "{}", values.value(key))?,
                None => writeln!(w, "cell_{}", i)?,
            }
        }
    } else {
        // Fallback: use Debug representation
        for i in 0..col.len() {
            writeln!(w, "cell_{}", i)?;
        }
    }

    w.flush()?;
    Ok(())
}

/// Write `features.tsv.gz` from var RecordBatch.
fn write_features_tsv(dir: &Path, var: &arrow::array::RecordBatch) -> Result<(), MtxError> {
    let path = dir.join("features.tsv.gz");
    let file = std::fs::File::create(&path)?;
    let gz = GzEncoder::new(file, Compression::default());
    let mut w = BufWriter::new(gz);

    if var.num_rows() == 0 {
        return Ok(());
    }

    let schema = var.schema();
    let n_rows = var.num_rows();

    // Try to find standard columns by name
    let id_col = find_string_column(var, &["gene_id", "id"]);
    let name_col = find_string_column(var, &["gene_name", "name"]);
    let type_col = find_string_column(var, &["feature_type"]);

    for i in 0..n_rows {
        let id = column_value_at(&id_col, var, i, &schema, 0);
        let name = column_value_at(&name_col, var, i, &schema, 1);

        if let Some(tc) = type_col {
            let ft = string_value(tc, i);
            writeln!(w, "{}\t{}\t{}", id, name, ft)?;
        } else {
            writeln!(w, "{}\t{}", id, name)?;
        }
    }

    w.flush()?;
    Ok(())
}

/// Find a StringArray column by trying candidate names.
fn find_string_column<'a>(
    batch: &'a arrow::array::RecordBatch,
    candidates: &[&str],
) -> Option<&'a arrow::array::StringArray> {
    let schema = batch.schema();
    for name in candidates {
        if let Ok(idx) = schema.index_of(name) {
            if let Some(arr) = batch
                .column(idx)
                .as_any()
                .downcast_ref::<arrow::array::StringArray>()
            {
                return Some(arr);
            }
        }
    }
    None
}

/// Get a string value from a column, with fallback to positional column or generated value.
fn column_value_at(
    col: &Option<&arrow::array::StringArray>,
    batch: &arrow::array::RecordBatch,
    row: usize,
    schema: &arrow::datatypes::SchemaRef,
    fallback_col_idx: usize,
) -> String {
    if let Some(arr) = col {
        return arr.value(row).to_string();
    }
    // Fallback: try positional column
    if fallback_col_idx < batch.num_columns() {
        if let Some(arr) = batch
            .column(fallback_col_idx)
            .as_any()
            .downcast_ref::<arrow::array::StringArray>()
        {
            return arr.value(row).to_string();
        }
    }
    // Last resort
    let _ = schema; // suppress unused warning
    format!("feature_{}", row)
}

/// Get string value from a StringArray.
fn string_value(arr: &arrow::array::StringArray, idx: usize) -> &str {
    arr.value(idx)
}

/// Write synthetic barcodes when obs is not available.
fn write_synthetic_barcodes(dir: &Path, n_obs: usize) -> Result<(), MtxError> {
    let path = dir.join("barcodes.tsv.gz");
    let file = std::fs::File::create(&path)?;
    let gz = GzEncoder::new(file, Compression::default());
    let mut w = BufWriter::new(gz);

    for i in 0..n_obs {
        writeln!(w, "cell_{}", i)?;
    }

    w.flush()?;
    Ok(())
}

/// Write synthetic features when var is not available.
fn write_synthetic_features(dir: &Path, n_vars: usize) -> Result<(), MtxError> {
    let path = dir.join("features.tsv.gz");
    let file = std::fs::File::create(&path)?;
    let gz = GzEncoder::new(file, Compression::default());
    let mut w = BufWriter::new(gz);

    for i in 0..n_vars {
        writeln!(w, "gene_{}\tGene{}\tGene Expression", i, i)?;
    }

    w.flush()?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use arrow::array::{RecordBatch, StringArray};
    use arrow::datatypes::{DataType, Field, Schema};
    use scx_codec::{CodecId, ValueEncoding};
    use scx_format_io::deletion_vectors::DeletionVectors;
    use scx_format_io::header::FileHeader;
    use scx_format_io::writer::ScxWriter;
    use std::io::Read;
    use std::sync::Arc;

    /// A 6×4 file, one nnz per row, with rows 1 and 4 logically deleted.
    fn write_fixture(dir: &tempfile::TempDir, deleted: &[u32]) -> std::path::PathBuf {
        let (n_obs, n_vars) = (6usize, 4usize);
        let path = dir.path().join("in.scx");
        let mut w = ScxWriter::new(
            &path,
            FileHeader {
                n_obs: n_obs as u64,
                n_vars: n_vars as u64,
                ..Default::default()
            },
        )
        .unwrap();

        let obs = RecordBatch::try_new(
            Arc::new(Schema::new(vec![Field::new(
                "cell_id",
                DataType::Utf8,
                false,
            )])),
            vec![Arc::new(StringArray::from(
                (0..n_obs).map(|i| format!("cell_{i}")).collect::<Vec<_>>(),
            ))],
        )
        .unwrap();
        w.write_obs(&obs).unwrap();
        let var = RecordBatch::try_new(
            Arc::new(Schema::new(vec![
                Field::new("gene_id", DataType::Utf8, false),
                Field::new("gene_name", DataType::Utf8, false),
            ])),
            vec![
                Arc::new(StringArray::from(
                    (0..n_vars).map(|i| format!("ENSG{i}")).collect::<Vec<_>>(),
                )),
                Arc::new(StringArray::from(
                    (0..n_vars).map(|i| format!("Gene{i}")).collect::<Vec<_>>(),
                )),
            ],
        )
        .unwrap();
        w.write_var(&var).unwrap();

        let mut indptr = vec![0u64];
        let (mut indices, mut values) = (Vec::new(), Vec::new());
        for row in 0..n_obs {
            indices.push((row % n_vars) as u32);
            values.push((row + 1) as u8);
            indptr.push(indptr.last().unwrap() + 1);
        }
        w.write_csr_shard(
            &indptr,
            &indices,
            &values,
            CodecId::None,
            ValueEncoding::Uint8,
            0,
        )
        .unwrap();

        if !deleted.is_empty() {
            let mut dv = DeletionVectors::new();
            dv.insert_global(deleted.iter().copied());
            w.write_deletion_vectors(&dv).unwrap();
        }
        w.finish().unwrap();
        path
    }

    fn read_gz(path: &Path) -> String {
        let f = std::fs::File::open(path).unwrap();
        let mut s = String::new();
        flate2::read::GzDecoder::new(f)
            .read_to_string(&mut s)
            .unwrap();
        s
    }

    /// MTX cannot represent a logical deletion, so the export has to apply it.
    ///
    /// The barcode count is asserted against the matrix size line rather than
    /// against a constant: a version of this bug that filtered X but not obs
    /// would still produce "6 barcodes", and would be the worse failure — an
    /// internally inconsistent directory rather than a merely stale one.
    #[test]
    fn mtx_export_omits_deleted_cells() {
        let dir = tempfile::tempdir().unwrap();
        let src = write_fixture(&dir, &[1, 4]);
        let out = dir.path().join("mtx");
        write_scx_to_mtx(&src, &out).unwrap();

        let barcodes: Vec<String> = read_gz(&out.join("barcodes.tsv.gz"))
            .lines()
            .map(|l| l.trim().to_string())
            .filter(|l| !l.is_empty())
            .collect();
        assert_eq!(
            barcodes,
            vec!["cell_0", "cell_2", "cell_3", "cell_5"],
            "the deleted cells must not appear, and the survivors keep their order"
        );

        // Size line is "n_vars n_obs nnz" (features × barcodes, Cell Ranger's
        // orientation — SCX-010).
        let mtx = read_gz(&out.join("matrix.mtx.gz"));
        let size_line = mtx
            .lines()
            .find(|l| !l.starts_with('%'))
            .expect("size line");
        let parts: Vec<usize> = size_line
            .split_whitespace()
            .map(|t| t.parse().unwrap())
            .collect();
        assert_eq!(parts[0], 4, "n_vars unchanged");
        assert_eq!(
            parts[1],
            barcodes.len(),
            "matrix column count must equal the barcode count"
        );
        assert_eq!(parts[2], 4, "one nnz per surviving row");
    }

    /// The no-deletions path must be untouched by the filter.
    #[test]
    fn mtx_export_without_deletions_writes_every_cell() {
        let dir = tempfile::tempdir().unwrap();
        let src = write_fixture(&dir, &[]);
        let out = dir.path().join("mtx");
        write_scx_to_mtx(&src, &out).unwrap();
        assert_eq!(
            read_gz(&out.join("barcodes.tsv.gz")).lines().count(),
            6,
            "no deletion vector: every cell is exported"
        );
    }
}
